# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主界面.ui',
# licensing of '主界面.ui' applies.
#
# Created: Mon Aug 10 08:40:33 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1175, 683)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/主题.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 505))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ZhuCaiDan = QtWidgets.QTabWidget(self.centralwidget)
        self.ZhuCaiDan.setEnabled(True)
        self.ZhuCaiDan.setMouseTracking(True)
        self.ZhuCaiDan.setTabletTracking(True)
        self.ZhuCaiDan.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ZhuCaiDan.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ZhuCaiDan.setAcceptDrops(True)
        self.ZhuCaiDan.setToolTipDuration(-1)
        self.ZhuCaiDan.setStatusTip("")
        self.ZhuCaiDan.setAutoFillBackground(False)
        self.ZhuCaiDan.setStyleSheet("")
        self.ZhuCaiDan.setDocumentMode(False)
        self.ZhuCaiDan.setTabsClosable(True)
        self.ZhuCaiDan.setMovable(False)
        self.ZhuCaiDan.setTabBarAutoHide(False)
        self.ZhuCaiDan.setObjectName("ZhuCaiDan")
        self.ranwu = QtWidgets.QWidget()
        self.ranwu.setObjectName("ranwu")
        self.ZhuCaiDan.addTab(self.ranwu, "")
        self.gridLayout_3.addWidget(self.ZhuCaiDan, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.caidan = QtWidgets.QMenuBar(MainWindow)
        self.caidan.setGeometry(QtCore.QRect(0, 0, 1175, 23))
        self.caidan.setObjectName("caidan")
        self.ren_shi = QtWidgets.QMenu(self.caidan)
        self.ren_shi.setObjectName("ren_shi")
        self.xiang_mu = QtWidgets.QMenu(self.caidan)
        self.xiang_mu.setObjectName("xiang_mu")
        self.sheng_chan = QtWidgets.QMenu(self.caidan)
        self.sheng_chan.setObjectName("sheng_chan")
        self.pin_zhi = QtWidgets.QMenu(self.caidan)
        self.pin_zhi.setObjectName("pin_zhi")
        self.chang_ku = QtWidgets.QMenu(self.caidan)
        self.chang_ku.setObjectName("chang_ku")
        self.cai_wu = QtWidgets.QMenu(self.caidan)
        self.cai_wu.setObjectName("cai_wu")
        self.ti_xi = QtWidgets.QMenu(self.caidan)
        self.ti_xi.setTearOffEnabled(False)
        self.ti_xi.setObjectName("ti_xi")
        self.zong_he_fen_xi = QtWidgets.QMenu(self.caidan)
        self.zong_he_fen_xi.setObjectName("zong_he_fen_xi")
        self.chang_yong_ruan_jian = QtWidgets.QMenu(self.caidan)
        self.chang_yong_ruan_jian.setObjectName("chang_yong_ruan_jian")
        self.bang_zhu = QtWidgets.QMenu(self.caidan)
        self.bang_zhu.setObjectName("bang_zhu")
        MainWindow.setMenuBar(self.caidan)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actFont_ranyuanchaxun = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(267).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_ranyuanchaxun.setIcon(icon1)
        self.actFont_ranyuanchaxun.setObjectName("actFont_ranyuanchaxun")
        self.加班记录 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ICO/png/1218679.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.加班记录.setIcon(icon2)
        self.加班记录.setObjectName("加班记录")
        self.请假记录 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/图标-07.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.请假记录.setIcon(icon3)
        self.请假记录.setObjectName("请假记录")
        self.考勤记录 = QtWidgets.QAction(MainWindow)
        self.考勤记录.setObjectName("考勤记录")
        self.后勤申请 = QtWidgets.QAction(MainWindow)
        self.后勤申请.setObjectName("后勤申请")
        self.actFont_xiangmuxinxi = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/图标-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actFont_xiangmuxinxi.setIcon(icon4)
        self.actFont_xiangmuxinxi.setObjectName("actFont_xiangmuxinxi")
        self.项目计划 = QtWidgets.QAction(MainWindow)
        self.项目计划.setObjectName("项目计划")
        self.机台安排 = QtWidgets.QAction(MainWindow)
        self.机台安排.setObjectName("机台安排")
        self.设备维修 = QtWidgets.QAction(MainWindow)
        self.设备维修.setObjectName("设备维修")
        self.产品信息 = QtWidgets.QAction(MainWindow)
        self.产品信息.setObjectName("产品信息")
        self.验模信息 = QtWidgets.QAction(MainWindow)
        self.验模信息.setObjectName("验模信息")
        self.检具管理 = QtWidgets.QAction(MainWindow)
        self.检具管理.setObjectName("检具管理")
        self.仪校管理 = QtWidgets.QAction(MainWindow)
        self.仪校管理.setObjectName("仪校管理")
        self.品质异常 = QtWidgets.QAction(MainWindow)
        self.品质异常.setObjectName("品质异常")
        self.交样信息 = QtWidgets.QAction(MainWindow)
        self.交样信息.setObjectName("交样信息")
        self.工程资料 = QtWidgets.QAction(MainWindow)
        self.工程资料.setObjectName("工程资料")
        self.详细清单 = QtWidgets.QAction(MainWindow)
        self.详细清单.setObjectName("详细清单")
        self.入库管理 = QtWidgets.QAction(MainWindow)
        self.入库管理.setObjectName("入库管理")
        self.出库管理 = QtWidgets.QAction(MainWindow)
        self.出库管理.setObjectName("出库管理")
        self.退货管理 = QtWidgets.QAction(MainWindow)
        self.退货管理.setObjectName("退货管理")
        self.借用管理 = QtWidgets.QAction(MainWindow)
        self.借用管理.setObjectName("借用管理")
        self.库存管理 = QtWidgets.QAction(MainWindow)
        self.库存管理.setObjectName("库存管理")
        self.报废清单 = QtWidgets.QAction(MainWindow)
        self.报废清单.setObjectName("报废清单")
        self.采购申请 = QtWidgets.QAction(MainWindow)
        self.采购申请.setObjectName("采购申请")
        self.品质一览 = QtWidgets.QAction(MainWindow)
        self.品质一览.setObjectName("品质一览")
        self.异常一览 = QtWidgets.QAction(MainWindow)
        self.异常一览.setObjectName("异常一览")
        self.进度一览 = QtWidgets.QAction(MainWindow)
        self.进度一览.setObjectName("进度一览")
        self.库存一览 = QtWidgets.QAction(MainWindow)
        self.库存一览.setObjectName("库存一览")
        self.截图软件 = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(3).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.截图软件.setIcon(icon5)
        self.截图软件.setObjectName("截图软件")
        self.翻译软件 = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(243).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.翻译软件.setIcon(icon6)
        self.翻译软件.setObjectName("翻译软件")
        self.日历 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/png/1234864.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.日历.setIcon(icon7)
        self.日历.setObjectName("日历")
        self.密码修改 = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(194).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.密码修改.setIcon(icon8)
        self.密码修改.setObjectName("密码修改")
        self.账号切换 = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(269).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.账号切换.setIcon(icon9)
        self.账号切换.setObjectName("账号切换")
        self.退出 = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ICO/ico/shell32.dll(240).ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.退出.setIcon(icon10)
        self.退出.setObjectName("退出")
        self.皮肤 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ICO/1142575.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.皮肤.setIcon(icon11)
        self.皮肤.setObjectName("皮肤")
        self.采购管理 = QtWidgets.QAction(MainWindow)
        self.采购管理.setObjectName("采购管理")
        self.外协管理 = QtWidgets.QAction(MainWindow)
        self.外协管理.setObjectName("外协管理")
        self.报销申请 = QtWidgets.QAction(MainWindow)
        self.报销申请.setObjectName("报销申请")
        self.体系查询 = QtWidgets.QAction(MainWindow)
        self.体系查询.setObjectName("体系查询")
        self.体系修改 = QtWidgets.QAction(MainWindow)
        self.体系修改.setObjectName("体系修改")
        self.actioncsdc = QtWidgets.QAction(MainWindow)
        self.actioncsdc.setObjectName("actioncsdc")
        self.ren_shi.addAction(self.actFont_ranyuanchaxun)
        self.ren_shi.addAction(self.请假记录)
        self.ren_shi.addAction(self.加班记录)
        self.ren_shi.addAction(self.考勤记录)
        self.ren_shi.addAction(self.后勤申请)
        self.xiang_mu.addAction(self.actFont_xiangmuxinxi)
        self.xiang_mu.addAction(self.项目计划)
        self.sheng_chan.addAction(self.工程资料)
        self.sheng_chan.addAction(self.机台安排)
        self.sheng_chan.addAction(self.设备维修)
        self.pin_zhi.addAction(self.产品信息)
        self.pin_zhi.addAction(self.验模信息)
        self.pin_zhi.addAction(self.检具管理)
        self.pin_zhi.addAction(self.仪校管理)
        self.pin_zhi.addAction(self.品质异常)
        self.pin_zhi.addAction(self.交样信息)
        self.chang_ku.addAction(self.详细清单)
        self.chang_ku.addAction(self.入库管理)
        self.chang_ku.addAction(self.出库管理)
        self.chang_ku.addAction(self.退货管理)
        self.chang_ku.addAction(self.借用管理)
        self.chang_ku.addAction(self.库存管理)
        self.chang_ku.addAction(self.报废清单)
        self.cai_wu.addAction(self.采购申请)
        self.cai_wu.addAction(self.报销申请)
        self.cai_wu.addSeparator()
        self.cai_wu.addAction(self.采购管理)
        self.cai_wu.addAction(self.外协管理)
        self.ti_xi.addAction(self.体系查询)
        self.ti_xi.addAction(self.体系修改)
        self.zong_he_fen_xi.addAction(self.品质一览)
        self.zong_he_fen_xi.addAction(self.异常一览)
        self.zong_he_fen_xi.addAction(self.进度一览)
        self.zong_he_fen_xi.addAction(self.库存一览)
        self.chang_yong_ruan_jian.addAction(self.截图软件)
        self.chang_yong_ruan_jian.addAction(self.翻译软件)
        self.chang_yong_ruan_jian.addAction(self.日历)
        self.bang_zhu.addAction(self.密码修改)
        self.bang_zhu.addAction(self.账号切换)
        self.bang_zhu.addAction(self.退出)
        self.bang_zhu.addSeparator()
        self.bang_zhu.addAction(self.皮肤)
        self.caidan.addAction(self.ren_shi.menuAction())
        self.caidan.addAction(self.xiang_mu.menuAction())
        self.caidan.addAction(self.sheng_chan.menuAction())
        self.caidan.addAction(self.pin_zhi.menuAction())
        self.caidan.addAction(self.chang_ku.menuAction())
        self.caidan.addAction(self.cai_wu.menuAction())
        self.caidan.addAction(self.ti_xi.menuAction())
        self.caidan.addAction(self.zong_he_fen_xi.menuAction())
        self.caidan.addAction(self.chang_yong_ruan_jian.menuAction())
        self.caidan.addAction(self.bang_zhu.menuAction())
        self.toolBar.addAction(self.actFont_ranyuanchaxun)
        self.toolBar.addAction(self.actFont_xiangmuxinxi)
        self.toolBar.addAction(self.加班记录)
        self.toolBar.addAction(self.请假记录)

        self.retranslateUi(MainWindow)
        self.ZhuCaiDan.setCurrentIndex(0)
        QtCore.QObject.connect(self.退出, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "飞云信息管理平台", None, -1))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.ranwu), QtWidgets.QApplication.translate("MainWindow", "任务栏", None, -1))
        self.ren_shi.setTitle(QtWidgets.QApplication.translate("MainWindow", "人事管理", None, -1))
        self.xiang_mu.setTitle(QtWidgets.QApplication.translate("MainWindow", "项目管理", None, -1))
        self.sheng_chan.setTitle(QtWidgets.QApplication.translate("MainWindow", "生产管理", None, -1))
        self.pin_zhi.setTitle(QtWidgets.QApplication.translate("MainWindow", "品质管理", None, -1))
        self.chang_ku.setTitle(QtWidgets.QApplication.translate("MainWindow", "仓库管理", None, -1))
        self.cai_wu.setTitle(QtWidgets.QApplication.translate("MainWindow", "财务管理", None, -1))
        self.ti_xi.setTitle(QtWidgets.QApplication.translate("MainWindow", "体系管理", None, -1))
        self.zong_he_fen_xi.setTitle(QtWidgets.QApplication.translate("MainWindow", "综合分析", None, -1))
        self.chang_yong_ruan_jian.setTitle(QtWidgets.QApplication.translate("MainWindow", "常用软件", None, -1))
        self.bang_zhu.setTitle(QtWidgets.QApplication.translate("MainWindow", "帮助", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.actFont_ranyuanchaxun.setText(QtWidgets.QApplication.translate("MainWindow", "人员查询", None, -1))
        self.加班记录.setText(QtWidgets.QApplication.translate("MainWindow", "加班记录", None, -1))
        self.请假记录.setText(QtWidgets.QApplication.translate("MainWindow", "请假记录", None, -1))
        self.考勤记录.setText(QtWidgets.QApplication.translate("MainWindow", "考勤记录", None, -1))
        self.后勤申请.setText(QtWidgets.QApplication.translate("MainWindow", "后勤申请", None, -1))
        self.actFont_xiangmuxinxi.setText(QtWidgets.QApplication.translate("MainWindow", "项目信息", None, -1))
        self.项目计划.setText(QtWidgets.QApplication.translate("MainWindow", "项目计划", None, -1))
        self.机台安排.setText(QtWidgets.QApplication.translate("MainWindow", "机台安排", None, -1))
        self.设备维修.setText(QtWidgets.QApplication.translate("MainWindow", "设备维修", None, -1))
        self.产品信息.setText(QtWidgets.QApplication.translate("MainWindow", "产品信息", None, -1))
        self.产品信息.setToolTip(QtWidgets.QApplication.translate("MainWindow", "产品信息", None, -1))
        self.验模信息.setText(QtWidgets.QApplication.translate("MainWindow", "验模信息", None, -1))
        self.验模信息.setToolTip(QtWidgets.QApplication.translate("MainWindow", "验模信息", None, -1))
        self.检具管理.setText(QtWidgets.QApplication.translate("MainWindow", "检具管理", None, -1))
        self.仪校管理.setText(QtWidgets.QApplication.translate("MainWindow", "仪校管理", None, -1))
        self.品质异常.setText(QtWidgets.QApplication.translate("MainWindow", "品质异常", None, -1))
        self.交样信息.setText(QtWidgets.QApplication.translate("MainWindow", "交样信息", None, -1))
        self.工程资料.setText(QtWidgets.QApplication.translate("MainWindow", "工程资料", None, -1))
        self.详细清单.setText(QtWidgets.QApplication.translate("MainWindow", "详细清单", None, -1))
        self.入库管理.setText(QtWidgets.QApplication.translate("MainWindow", "入库管理", None, -1))
        self.出库管理.setText(QtWidgets.QApplication.translate("MainWindow", "出库管理", None, -1))
        self.退货管理.setText(QtWidgets.QApplication.translate("MainWindow", "退货管理", None, -1))
        self.借用管理.setText(QtWidgets.QApplication.translate("MainWindow", "借用管理", None, -1))
        self.库存管理.setText(QtWidgets.QApplication.translate("MainWindow", "库存管理", None, -1))
        self.报废清单.setText(QtWidgets.QApplication.translate("MainWindow", "报废清单", None, -1))
        self.采购申请.setText(QtWidgets.QApplication.translate("MainWindow", "采购申请", None, -1))
        self.品质一览.setText(QtWidgets.QApplication.translate("MainWindow", "品质一览", None, -1))
        self.异常一览.setText(QtWidgets.QApplication.translate("MainWindow", "异常一览", None, -1))
        self.进度一览.setText(QtWidgets.QApplication.translate("MainWindow", "进度一览", None, -1))
        self.库存一览.setText(QtWidgets.QApplication.translate("MainWindow", "库存一览", None, -1))
        self.截图软件.setText(QtWidgets.QApplication.translate("MainWindow", "截图软件", None, -1))
        self.翻译软件.setText(QtWidgets.QApplication.translate("MainWindow", "翻译软件", None, -1))
        self.日历.setText(QtWidgets.QApplication.translate("MainWindow", "日历", None, -1))
        self.密码修改.setText(QtWidgets.QApplication.translate("MainWindow", "密码修改", None, -1))
        self.密码修改.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+E", None, -1))
        self.账号切换.setText(QtWidgets.QApplication.translate("MainWindow", "账号切换", None, -1))
        self.账号切换.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+W", None, -1))
        self.退出.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.退出.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "点击按钮退出程序！", None, -1))
        self.退出.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))
        self.皮肤.setText(QtWidgets.QApplication.translate("MainWindow", "皮肤", None, -1))
        self.采购管理.setText(QtWidgets.QApplication.translate("MainWindow", "采购管理", None, -1))
        self.外协管理.setText(QtWidgets.QApplication.translate("MainWindow", "外协管理", None, -1))
        self.报销申请.setText(QtWidgets.QApplication.translate("MainWindow", "报销申请", None, -1))
        self.体系查询.setText(QtWidgets.QApplication.translate("MainWindow", "体系查询", None, -1))
        self.体系修改.setText(QtWidgets.QApplication.translate("MainWindow", "体系修改", None, -1))
        self.actioncsdc.setText(QtWidgets.QApplication.translate("MainWindow", "csdc", None, -1))

