# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '主界面.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject,
                            QRect, QSize, Qt)
from PySide2.QtGui import (QIcon)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1175, 683)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/new/prefix1/ICO/\u4e3b\u9898.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.actFont_ranyuanchaxun = QAction(MainWindow)
        self.actFont_ranyuanchaxun.setObjectName(u"actFont_ranyuanchaxun")
        icon1 = QIcon()
        icon1.addFile(u":/new/prefix1/ICO/png/shell32.dll(267).png", QSize(), QIcon.Normal, QIcon.Off)
        self.actFont_ranyuanchaxun.setIcon(icon1)
        self.加班记录 = QAction(MainWindow)
        self.加班记录.setObjectName(u"\u52a0\u73ed\u8bb0\u5f55")
        icon2 = QIcon()
        icon2.addFile(u":/new/prefix1/ICO/png/1218679.png", QSize(), QIcon.Normal, QIcon.Off)
        self.加班记录.setIcon(icon2)
        self.请假记录 = QAction(MainWindow)
        self.请假记录.setObjectName(u"\u8bf7\u5047\u8bb0\u5f55")
        icon3 = QIcon()
        icon3.addFile(u":/new/prefix1/ICO/\u56fe\u6807-07.png", QSize(), QIcon.Normal, QIcon.Off)
        self.请假记录.setIcon(icon3)
        self.考勤记录 = QAction(MainWindow)
        self.考勤记录.setObjectName(u"\u8003\u52e4\u8bb0\u5f55")
        self.后勤申请 = QAction(MainWindow)
        self.后勤申请.setObjectName(u"\u540e\u52e4\u7533\u8bf7")
        self.actFont_xiangmuxinxi = QAction(MainWindow)
        self.actFont_xiangmuxinxi.setObjectName(u"actFont_xiangmuxinxi")
        icon4 = QIcon()
        icon4.addFile(u":/new/prefix1/ICO/\u56fe\u6807-02.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actFont_xiangmuxinxi.setIcon(icon4)
        self.项目计划 = QAction(MainWindow)
        self.项目计划.setObjectName(u"\u9879\u76ee\u8ba1\u5212")
        self.机台安排 = QAction(MainWindow)
        self.机台安排.setObjectName(u"\u673a\u53f0\u5b89\u6392")
        self.设备维修 = QAction(MainWindow)
        self.设备维修.setObjectName(u"\u8bbe\u5907\u7ef4\u4fee")
        self.产品信息 = QAction(MainWindow)
        self.产品信息.setObjectName(u"\u4ea7\u54c1\u4fe1\u606f")
        self.验模信息 = QAction(MainWindow)
        self.验模信息.setObjectName(u"\u9a8c\u6a21\u4fe1\u606f")
        self.检具管理 = QAction(MainWindow)
        self.检具管理.setObjectName(u"\u68c0\u5177\u7ba1\u7406")
        self.仪校管理 = QAction(MainWindow)
        self.仪校管理.setObjectName(u"\u4eea\u6821\u7ba1\u7406")
        self.品质异常 = QAction(MainWindow)
        self.品质异常.setObjectName(u"\u54c1\u8d28\u5f02\u5e38")
        self.交样信息 = QAction(MainWindow)
        self.交样信息.setObjectName(u"\u4ea4\u6837\u4fe1\u606f")
        self.工程资料 = QAction(MainWindow)
        self.工程资料.setObjectName(u"\u5de5\u7a0b\u8d44\u6599")
        self.详细清单 = QAction(MainWindow)
        self.详细清单.setObjectName(u"\u8be6\u7ec6\u6e05\u5355")
        self.入库管理 = QAction(MainWindow)
        self.入库管理.setObjectName(u"\u5165\u5e93\u7ba1\u7406")
        self.出库管理 = QAction(MainWindow)
        self.出库管理.setObjectName(u"\u51fa\u5e93\u7ba1\u7406")
        self.退货管理 = QAction(MainWindow)
        self.退货管理.setObjectName(u"\u9000\u8d27\u7ba1\u7406")
        self.借用管理 = QAction(MainWindow)
        self.借用管理.setObjectName(u"\u501f\u7528\u7ba1\u7406")
        self.库存管理 = QAction(MainWindow)
        self.库存管理.setObjectName(u"\u5e93\u5b58\u7ba1\u7406")
        self.报废清单 = QAction(MainWindow)
        self.报废清单.setObjectName(u"\u62a5\u5e9f\u6e05\u5355")
        self.采购申请 = QAction(MainWindow)
        self.采购申请.setObjectName(u"\u91c7\u8d2d\u7533\u8bf7")
        self.品质一览 = QAction(MainWindow)
        self.品质一览.setObjectName(u"\u54c1\u8d28\u4e00\u89c8")
        self.异常一览 = QAction(MainWindow)
        self.异常一览.setObjectName(u"\u5f02\u5e38\u4e00\u89c8")
        self.进度一览 = QAction(MainWindow)
        self.进度一览.setObjectName(u"\u8fdb\u5ea6\u4e00\u89c8")
        self.库存一览 = QAction(MainWindow)
        self.库存一览.setObjectName(u"\u5e93\u5b58\u4e00\u89c8")
        self.截图软件 = QAction(MainWindow)
        self.截图软件.setObjectName(u"\u622a\u56fe\u8f6f\u4ef6")
        icon5 = QIcon()
        icon5.addFile(u":/new/prefix1/ICO/png/shell32.dll(3).png", QSize(), QIcon.Normal, QIcon.Off)
        self.截图软件.setIcon(icon5)
        self.翻译软件 = QAction(MainWindow)
        self.翻译软件.setObjectName(u"\u7ffb\u8bd1\u8f6f\u4ef6")
        icon6 = QIcon()
        icon6.addFile(u":/new/prefix1/ICO/png/shell32.dll(243).png", QSize(), QIcon.Normal, QIcon.Off)
        self.翻译软件.setIcon(icon6)
        self.日历 = QAction(MainWindow)
        self.日历.setObjectName(u"\u65e5\u5386")
        icon7 = QIcon()
        icon7.addFile(u":/new/prefix1/ICO/png/1234864.png", QSize(), QIcon.Normal, QIcon.Off)
        self.日历.setIcon(icon7)
        self.密码修改 = QAction(MainWindow)
        self.密码修改.setObjectName(u"\u5bc6\u7801\u4fee\u6539")
        icon8 = QIcon()
        icon8.addFile(u":/new/prefix1/ICO/png/shell32.dll(194).png", QSize(), QIcon.Normal, QIcon.Off)
        self.密码修改.setIcon(icon8)
        self.账号切换 = QAction(MainWindow)
        self.账号切换.setObjectName(u"\u8d26\u53f7\u5207\u6362")
        icon9 = QIcon()
        icon9.addFile(u":/new/prefix1/ICO/png/shell32.dll(269).png", QSize(), QIcon.Normal, QIcon.Off)
        self.账号切换.setIcon(icon9)
        self.退出 = QAction(MainWindow)
        self.退出.setObjectName(u"\u9000\u51fa")
        icon10 = QIcon()
        icon10.addFile(u":/new/prefix1/ICO/png/shell32.dll(240).png", QSize(), QIcon.Normal, QIcon.Off)
        self.退出.setIcon(icon10)
        self.皮肤 = QAction(MainWindow)
        self.皮肤.setObjectName(u"\u76ae\u80a4")
        icon11 = QIcon()
        icon11.addFile(u"ICO/1142575.png", QSize(), QIcon.Normal, QIcon.Off)
        self.皮肤.setIcon(icon11)
        self.采购管理 = QAction(MainWindow)
        self.采购管理.setObjectName(u"\u91c7\u8d2d\u7ba1\u7406")
        self.外协管理 = QAction(MainWindow)
        self.外协管理.setObjectName(u"\u5916\u534f\u7ba1\u7406")
        self.报销申请 = QAction(MainWindow)
        self.报销申请.setObjectName(u"\u62a5\u9500\u7533\u8bf7")
        self.体系查询 = QAction(MainWindow)
        self.体系查询.setObjectName(u"\u4f53\u7cfb\u67e5\u8be2")
        self.体系修改 = QAction(MainWindow)
        self.体系修改.setObjectName(u"\u4f53\u7cfb\u4fee\u6539")
        self.actioncsdc = QAction(MainWindow)
        self.actioncsdc.setObjectName(u"actioncsdc")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(800, 505))
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.ZhuCaiDan = QTabWidget(self.centralwidget)
        self.ZhuCaiDan.setObjectName(u"ZhuCaiDan")
        self.ZhuCaiDan.setEnabled(True)
        self.ZhuCaiDan.setMouseTracking(True)
        self.ZhuCaiDan.setTabletTracking(True)
        self.ZhuCaiDan.setFocusPolicy(Qt.ClickFocus)
        self.ZhuCaiDan.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.ZhuCaiDan.setAcceptDrops(True)
        self.ZhuCaiDan.setToolTipDuration(-1)
        self.ZhuCaiDan.setAutoFillBackground(False)
        self.ZhuCaiDan.setStyleSheet(u"")
        self.ZhuCaiDan.setDocumentMode(False)
        self.ZhuCaiDan.setTabsClosable(True)
        self.ZhuCaiDan.setMovable(False)
        self.ZhuCaiDan.setTabBarAutoHide(False)
        self.ranwu = QWidget()
        self.ranwu.setObjectName(u"ranwu")
        self.ZhuCaiDan.addTab(self.ranwu, "")

        self.gridLayout_3.addWidget(self.ZhuCaiDan, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.caidan = QMenuBar(MainWindow)
        self.caidan.setObjectName(u"caidan")
        self.caidan.setGeometry(QRect(0, 0, 1175, 23))
        self.ren_shi = QMenu(self.caidan)
        self.ren_shi.setObjectName(u"ren_shi")
        self.xiang_mu = QMenu(self.caidan)
        self.xiang_mu.setObjectName(u"xiang_mu")
        self.sheng_chan = QMenu(self.caidan)
        self.sheng_chan.setObjectName(u"sheng_chan")
        self.pin_zhi = QMenu(self.caidan)
        self.pin_zhi.setObjectName(u"pin_zhi")
        self.chang_ku = QMenu(self.caidan)
        self.chang_ku.setObjectName(u"chang_ku")
        self.cai_wu = QMenu(self.caidan)
        self.cai_wu.setObjectName(u"cai_wu")
        self.ti_xi = QMenu(self.caidan)
        self.ti_xi.setObjectName(u"ti_xi")
        self.ti_xi.setTearOffEnabled(False)
        self.zong_he_fen_xi = QMenu(self.caidan)
        self.zong_he_fen_xi.setObjectName(u"zong_he_fen_xi")
        self.chang_yong_ruan_jian = QMenu(self.caidan)
        self.chang_yong_ruan_jian.setObjectName(u"chang_yong_ruan_jian")
        self.bang_zhu = QMenu(self.caidan)
        self.bang_zhu.setObjectName(u"bang_zhu")
        MainWindow.setMenuBar(self.caidan)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setLayoutDirection(Qt.LeftToRight)
        self.toolBar.setAllowedAreas(Qt.AllToolBarAreas)
        self.toolBar.setOrientation(Qt.Vertical)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.caidan.addAction(self.ren_shi.menuAction())
        self.caidan.addAction(self.xiang_mu.menuAction())
        self.caidan.addAction(self.sheng_chan.menuAction())
        self.caidan.addAction(self.pin_zhi.menuAction())
        self.caidan.addAction(self.chang_ku.menuAction())
        self.caidan.addAction(self.cai_wu.menuAction())
        self.caidan.addAction(self.ti_xi.menuAction())
        self.caidan.addAction(self.zong_he_fen_xi.menuAction())
        self.caidan.addAction(self.chang_yong_ruan_jian.menuAction())
        self.caidan.addAction(self.bang_zhu.menuAction())
        self.ren_shi.addAction(self.actFont_ranyuanchaxun)
        self.ren_shi.addAction(self.请假记录)
        self.ren_shi.addAction(self.加班记录)
        self.ren_shi.addAction(self.考勤记录)
        self.ren_shi.addAction(self.后勤申请)
        self.xiang_mu.addAction(self.actFont_xiangmuxinxi)
        self.xiang_mu.addAction(self.项目计划)
        self.sheng_chan.addAction(self.工程资料)
        self.sheng_chan.addAction(self.机台安排)
        self.sheng_chan.addAction(self.设备维修)
        self.pin_zhi.addAction(self.产品信息)
        self.pin_zhi.addAction(self.验模信息)
        self.pin_zhi.addAction(self.检具管理)
        self.pin_zhi.addAction(self.仪校管理)
        self.pin_zhi.addAction(self.品质异常)
        self.pin_zhi.addAction(self.交样信息)
        self.chang_ku.addAction(self.详细清单)
        self.chang_ku.addAction(self.入库管理)
        self.chang_ku.addAction(self.出库管理)
        self.chang_ku.addAction(self.退货管理)
        self.chang_ku.addAction(self.借用管理)
        self.chang_ku.addAction(self.库存管理)
        self.chang_ku.addAction(self.报废清单)
        self.cai_wu.addAction(self.采购申请)
        self.cai_wu.addAction(self.报销申请)
        self.cai_wu.addSeparator()
        self.cai_wu.addAction(self.采购管理)
        self.cai_wu.addAction(self.外协管理)
        self.ti_xi.addAction(self.体系查询)
        self.ti_xi.addAction(self.体系修改)
        self.zong_he_fen_xi.addAction(self.品质一览)
        self.zong_he_fen_xi.addAction(self.异常一览)
        self.zong_he_fen_xi.addAction(self.进度一览)
        self.zong_he_fen_xi.addAction(self.库存一览)
        self.chang_yong_ruan_jian.addAction(self.截图软件)
        self.chang_yong_ruan_jian.addAction(self.翻译软件)
        self.chang_yong_ruan_jian.addAction(self.日历)
        self.bang_zhu.addAction(self.密码修改)
        self.bang_zhu.addAction(self.账号切换)
        self.bang_zhu.addAction(self.退出)
        self.bang_zhu.addSeparator()
        self.bang_zhu.addAction(self.皮肤)
        self.toolBar.addAction(self.actFont_ranyuanchaxun)
        self.toolBar.addAction(self.actFont_xiangmuxinxi)
        self.toolBar.addAction(self.加班记录)
        self.toolBar.addAction(self.请假记录)

        self.retranslateUi(MainWindow)
        self.退出.triggered.connect(MainWindow.close)

        self.ZhuCaiDan.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u98de\u4e91\u4fe1\u606f\u7ba1\u7406\u5e73\u53f0", None))
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.actFont_ranyuanchaxun.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u5458\u67e5\u8be2", None))
        self.加班记录.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u73ed\u8bb0\u5f55", None))
        self.请假记录.setText(QCoreApplication.translate("MainWindow", u"\u8bf7\u5047\u8bb0\u5f55", None))
        self.考勤记录.setText(QCoreApplication.translate("MainWindow", u"\u8003\u52e4\u8bb0\u5f55", None))
        self.后勤申请.setText(QCoreApplication.translate("MainWindow", u"\u540e\u52e4\u7533\u8bf7", None))
        self.actFont_xiangmuxinxi.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u4fe1\u606f", None))
        self.项目计划.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u8ba1\u5212", None))
        self.机台安排.setText(QCoreApplication.translate("MainWindow", u"\u673a\u53f0\u5b89\u6392", None))
        self.设备维修.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u7ef4\u4fee", None))
        self.产品信息.setText(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u4fe1\u606f", None))
#if QT_CONFIG(tooltip)
        self.产品信息.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.验模信息.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u4fe1\u606f", None))
#if QT_CONFIG(tooltip)
        self.验模信息.setToolTip(QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.检具管理.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u5177\u7ba1\u7406", None))
        self.仪校管理.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u6821\u7ba1\u7406", None))
        self.品质异常.setText(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u5f02\u5e38", None))
        self.交样信息.setText(QCoreApplication.translate("MainWindow", u"\u4ea4\u6837\u4fe1\u606f", None))
        self.工程资料.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u7a0b\u8d44\u6599", None))
        self.详细清单.setText(QCoreApplication.translate("MainWindow", u"\u8be6\u7ec6\u6e05\u5355", None))
        self.入库管理.setText(QCoreApplication.translate("MainWindow", u"\u5165\u5e93\u7ba1\u7406", None))
        self.出库管理.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u5e93\u7ba1\u7406", None))
        self.退货管理.setText(QCoreApplication.translate("MainWindow", u"\u9000\u8d27\u7ba1\u7406", None))
        self.借用管理.setText(QCoreApplication.translate("MainWindow", u"\u501f\u7528\u7ba1\u7406", None))
        self.库存管理.setText(QCoreApplication.translate("MainWindow", u"\u5e93\u5b58\u7ba1\u7406", None))
        self.报废清单.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u5e9f\u6e05\u5355", None))
        self.采购申请.setText(QCoreApplication.translate("MainWindow", u"\u91c7\u8d2d\u7533\u8bf7", None))
        self.品质一览.setText(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u4e00\u89c8", None))
        self.异常一览.setText(QCoreApplication.translate("MainWindow", u"\u5f02\u5e38\u4e00\u89c8", None))
        self.进度一览.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u5ea6\u4e00\u89c8", None))
        self.库存一览.setText(QCoreApplication.translate("MainWindow", u"\u5e93\u5b58\u4e00\u89c8", None))
        self.截图软件.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe\u8f6f\u4ef6", None))
        self.翻译软件.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\u8f6f\u4ef6", None))
        self.日历.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u5386", None))
        self.密码修改.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u7801\u4fee\u6539", None))
#if QT_CONFIG(shortcut)
        self.密码修改.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.账号切换.setText(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\u5207\u6362", None))
#if QT_CONFIG(shortcut)
        self.账号切换.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.退出.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(statustip)
        self.退出.setStatusTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u6309\u94ae\u9000\u51fa\u7a0b\u5e8f\uff01", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.退出.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.皮肤.setText(QCoreApplication.translate("MainWindow", u"\u76ae\u80a4", None))
        self.采购管理.setText(QCoreApplication.translate("MainWindow", u"\u91c7\u8d2d\u7ba1\u7406", None))
        self.外协管理.setText(QCoreApplication.translate("MainWindow", u"\u5916\u534f\u7ba1\u7406", None))
        self.报销申请.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u9500\u7533\u8bf7", None))
        self.体系查询.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u67e5\u8be2", None))
        self.体系修改.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u4fee\u6539", None))
        self.actioncsdc.setText(QCoreApplication.translate("MainWindow", u"csdc", None))
#if QT_CONFIG(statustip)
        self.ZhuCaiDan.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.ranwu), QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u680f", None))
        self.ren_shi.setTitle(QCoreApplication.translate("MainWindow", u"\u4eba\u4e8b\u7ba1\u7406", None))
        self.xiang_mu.setTitle(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u7ba1\u7406", None))
        self.sheng_chan.setTitle(QCoreApplication.translate("MainWindow", u"\u751f\u4ea7\u7ba1\u7406", None))
        self.pin_zhi.setTitle(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u7ba1\u7406", None))
        self.chang_ku.setTitle(QCoreApplication.translate("MainWindow", u"\u4ed3\u5e93\u7ba1\u7406", None))
        self.cai_wu.setTitle(QCoreApplication.translate("MainWindow", u"\u8d22\u52a1\u7ba1\u7406", None))
        self.ti_xi.setTitle(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u7ba1\u7406", None))
        self.zong_he_fen_xi.setTitle(QCoreApplication.translate("MainWindow", u"\u7efc\u5408\u5206\u6790", None))
        self.chang_yong_ruan_jian.setTitle(QCoreApplication.translate("MainWindow", u"\u5e38\u7528\u8f6f\u4ef6", None))
        self.bang_zhu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

