# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '人员信息录入.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(635, 363)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QIcon()
        icon.addFile(u"ICO/\u4e3b\u9898.png", QSize(), QIcon.Normal, QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 41, 21))
        font1 = QFont()
        font1.setFamily(u"\u5b8b\u4f53")
        font1.setPointSize(12)
        self.label.setFont(font1)
        self.xingming = QLineEdit(Dialog)
        self.xingming.setObjectName(u"xingming")
        self.xingming.setGeometry(QRect(50, 10, 81, 21))
        self.xingming.setLayoutDirection(Qt.LeftToRight)
        self.xingming.setAutoFillBackground(False)
        self.xingming.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 10, 41, 21))
        self.label_2.setFont(font1)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 40, 41, 21))
        self.label_3.setFont(font1)
        self.bumen = QLineEdit(Dialog)
        self.bumen.setObjectName(u"bumen")
        self.bumen.setGeometry(QRect(50, 40, 121, 21))
        self.bumen.setLayoutDirection(Qt.LeftToRight)
        self.bumen.setAutoFillBackground(False)
        self.bumen.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.zhiwei = QLineEdit(Dialog)
        self.zhiwei.setObjectName(u"zhiwei")
        self.zhiwei.setGeometry(QRect(50, 70, 91, 21))
        self.zhiwei.setLayoutDirection(Qt.LeftToRight)
        self.zhiwei.setAutoFillBackground(False)
        self.zhiwei.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 70, 41, 21))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 70, 41, 21))
        self.label_5.setFont(font1)
        self.gonghao = QLineEdit(Dialog)
        self.gonghao.setObjectName(u"gonghao")
        self.gonghao.setGeometry(QRect(190, 70, 71, 21))
        self.gonghao.setLayoutDirection(Qt.LeftToRight)
        self.gonghao.setAutoFillBackground(False)
        self.gonghao.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 160, 41, 21))
        self.label_6.setFont(font1)
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(180, 40, 41, 21))
        self.label_7.setFont(font1)
        self.zubie = QLineEdit(Dialog)
        self.zubie.setObjectName(u"zubie")
        self.zubie.setGeometry(QRect(220, 40, 171, 21))
        self.zubie.setLayoutDirection(Qt.LeftToRight)
        self.zubie.setAutoFillBackground(False)
        self.zubie.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(230, 10, 71, 21))
        self.label_8.setFont(font1)
        self.ruzhiriqi = QLineEdit(Dialog)
        self.ruzhiriqi.setObjectName(u"ruzhiriqi")
        self.ruzhiriqi.setGeometry(QRect(300, 10, 91, 21))
        self.ruzhiriqi.setLayoutDirection(Qt.LeftToRight)
        self.ruzhiriqi.setAutoFillBackground(False)
        self.ruzhiriqi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lianxidianhua = QLineEdit(Dialog)
        self.lianxidianhua.setObjectName(u"lianxidianhua")
        self.lianxidianhua.setGeometry(QRect(80, 100, 121, 21))
        self.lianxidianhua.setLayoutDirection(Qt.LeftToRight)
        self.lianxidianhua.setAutoFillBackground(False)
        self.lianxidianhua.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 100, 71, 21))
        self.label_9.setFont(font1)
        self.xingbie = QComboBox(Dialog)
        self.xingbie.addItem("")
        self.xingbie.addItem("")
        self.xingbie.addItem("")
        self.xingbie.setObjectName(u"xingbie")
        self.xingbie.setEnabled(True)
        self.xingbie.setGeometry(QRect(180, 10, 41, 22))
        self.xingbie.setEditable(True)
        self.xingbie.setFrame(True)
        self.jinjilianxihaoma = QLineEdit(Dialog)
        self.jinjilianxihaoma.setObjectName(u"jinjilianxihaoma")
        self.jinjilianxihaoma.setGeometry(QRect(270, 130, 121, 21))
        self.jinjilianxihaoma.setLayoutDirection(Qt.LeftToRight)
        self.jinjilianxihaoma.setAutoFillBackground(False)
        self.jinjilianxihaoma.setMaxLength(11)
        self.jinjilianxihaoma.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 130, 101, 21))
        self.label_10.setFont(font1)
        self.jinjilianxiren = QLineEdit(Dialog)
        self.jinjilianxiren.setObjectName(u"jinjilianxiren")
        self.jinjilianxiren.setGeometry(QRect(100, 130, 71, 21))
        self.jinjilianxiren.setLayoutDirection(Qt.LeftToRight)
        self.jinjilianxiren.setAutoFillBackground(False)
        self.jinjilianxiren.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 130, 91, 21))
        self.label_11.setFont(font1)
        self.chushengriqi = QLineEdit(Dialog)
        self.chushengriqi.setObjectName(u"chushengriqi")
        self.chushengriqi.setGeometry(QRect(290, 100, 101, 21))
        self.chushengriqi.setLayoutDirection(Qt.LeftToRight)
        self.chushengriqi.setAutoFillBackground(False)
        self.chushengriqi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.chushengriqi.setReadOnly(True)
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 100, 71, 21))
        self.label_13.setFont(font1)
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 190, 91, 21))
        self.shenfenzhenghaoma = QLineEdit(Dialog)
        self.shenfenzhenghaoma.setObjectName(u"shenfenzhenghaoma")
        self.shenfenzhenghaoma.setGeometry(QRect(100, 190, 291, 21))
        self.shenfenzhenghaoma.setLayoutDirection(Qt.LeftToRight)
        self.shenfenzhenghaoma.setAutoFillBackground(False)
        self.shenfenzhenghaoma.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dizhi = QLineEdit(Dialog)
        self.dizhi.setObjectName(u"dizhi")
        self.dizhi.setGeometry(QRect(50, 220, 341, 21))
        self.dizhi.setLayoutDirection(Qt.LeftToRight)
        self.dizhi.setAutoFillBackground(False)
        self.dizhi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_16 = QLabel(Dialog)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 220, 41, 21))
        self.label_16.setFont(font1)
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 70, 71, 21))
        self.label_12.setFont(font1)
        self.gongzuonianfen = QLineEdit(Dialog)
        self.gongzuonianfen.setObjectName(u"gongzuonianfen")
        self.gongzuonianfen.setGeometry(QRect(340, 70, 51, 21))
        self.gongzuonianfen.setLayoutDirection(Qt.LeftToRight)
        self.gongzuonianfen.setAutoFillBackground(False)
        self.gongzuonianfen.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tiaoxinriqi = QLineEdit(Dialog)
        self.tiaoxinriqi.setObjectName(u"tiaoxinriqi")
        self.tiaoxinriqi.setGeometry(QRect(270, 160, 121, 21))
        self.tiaoxinriqi.setLayoutDirection(Qt.LeftToRight)
        self.tiaoxinriqi.setAutoFillBackground(False)
        self.tiaoxinriqi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(200, 160, 71, 21))
        self.label_15.setFont(font1)
        self.label_17 = QLabel(Dialog)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 280, 41, 21))
        self.label_17.setFont(font1)
        self.beizhu = QLineEdit(Dialog)
        self.beizhu.setObjectName(u"beizhu")
        self.beizhu.setGeometry(QRect(50, 280, 341, 81))
        self.beizhu.setLayoutDirection(Qt.LeftToRight)
        self.beizhu.setAutoFillBackground(False)
        self.beizhu.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.queren = QPushButton(Dialog)
        self.queren.setObjectName(u"queren")
        self.queren.setGeometry(QRect(400, 290, 231, 31))
        self.chongzhi = QPushButton(Dialog)
        self.chongzhi.setObjectName(u"chongzhi")
        self.chongzhi.setGeometry(QRect(400, 330, 231, 31))
        self.paizhao = QPushButton(Dialog)
        self.paizhao.setObjectName(u"paizhao")
        self.paizhao.setGeometry(QRect(550, 250, 81, 31))
        self.dakaixiangji = QPushButton(Dialog)
        self.dakaixiangji.setObjectName(u"dakaixiangji")
        self.dakaixiangji.setGeometry(QRect(410, 250, 81, 31))
        self.daiyu = QDoubleSpinBox(Dialog)
        self.daiyu.setObjectName(u"daiyu")
        self.daiyu.setGeometry(QRect(50, 160, 121, 22))
        self.daiyu.setDecimals(2)
        self.daiyu.setMaximum(999999999.990000009536743)
        self.widget = QWidget(Dialog)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(390, 0, 241, 251))
        self.lizhiriqi = QLineEdit(Dialog)
        self.lizhiriqi.setObjectName(u"lizhiriqi")
        self.lizhiriqi.setGeometry(QRect(270, 250, 121, 21))
        self.lizhiriqi.setLayoutDirection(Qt.LeftToRight)
        self.lizhiriqi.setAutoFillBackground(False)
        self.lizhiriqi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lizhiriqi.setReadOnly(True)
        self.label_18 = QLabel(Dialog)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 250, 71, 21))
        self.label_18.setFont(font1)
        self.hetongriqi = QLineEdit(Dialog)
        self.hetongriqi.setObjectName(u"hetongriqi")
        self.hetongriqi.setGeometry(QRect(80, 250, 111, 21))
        self.hetongriqi.setLayoutDirection(Qt.LeftToRight)
        self.hetongriqi.setAutoFillBackground(False)
        self.hetongriqi.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_19 = QLabel(Dialog)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(200, 250, 71, 21))
        self.label_19.setFont(font1)
        QWidget.setTabOrder(self.xingming, self.ruzhiriqi)
        QWidget.setTabOrder(self.ruzhiriqi, self.bumen)
        QWidget.setTabOrder(self.bumen, self.zubie)
        QWidget.setTabOrder(self.zubie, self.zhiwei)
        QWidget.setTabOrder(self.zhiwei, self.gonghao)
        QWidget.setTabOrder(self.gonghao, self.gongzuonianfen)
        QWidget.setTabOrder(self.gongzuonianfen, self.lianxidianhua)
        QWidget.setTabOrder(self.lianxidianhua, self.jinjilianxiren)
        QWidget.setTabOrder(self.jinjilianxiren, self.jinjilianxihaoma)
        QWidget.setTabOrder(self.jinjilianxihaoma, self.daiyu)
        QWidget.setTabOrder(self.daiyu, self.shenfenzhenghaoma)
        QWidget.setTabOrder(self.shenfenzhenghaoma, self.dizhi)
        QWidget.setTabOrder(self.dizhi, self.beizhu)
        QWidget.setTabOrder(self.beizhu, self.dakaixiangji)
        QWidget.setTabOrder(self.dakaixiangji, self.paizhao)
        QWidget.setTabOrder(self.paizhao, self.queren)
        QWidget.setTabOrder(self.queren, self.chongzhi)
        QWidget.setTabOrder(self.chongzhi, self.tiaoxinriqi)
        QWidget.setTabOrder(self.tiaoxinriqi, self.chushengriqi)
        QWidget.setTabOrder(self.chushengriqi, self.xingbie)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"\u4eba\u5458\u4fe1\u606f", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"\u59d3\u540d:", None))
        self.xingming.setInputMask("")
        self.label_2.setText(QCoreApplication.translate("Dialog", u"\u6027\u522b:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"\u90e8\u95e8:", None))
        self.bumen.setInputMask("")
        self.zhiwei.setInputMask("")
        self.zhiwei.setText("")
        self.label_4.setText(QCoreApplication.translate("Dialog", u"\u804c\u4f4d:", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"\u5de5\u53f7:", None))
        self.gonghao.setInputMask("")
        self.gonghao.setText("")
        self.label_6.setText(QCoreApplication.translate("Dialog", u"\u5f85\u9047:", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"\u7ec4\u522b:", None))
        self.zubie.setInputMask("")
        self.zubie.setText("")
        self.label_8.setText(QCoreApplication.translate("Dialog", u"\u5165\u804c\u65e5\u671f:", None))
        self.ruzhiriqi.setInputMask("")
        self.ruzhiriqi.setText("")
        self.lianxidianhua.setInputMask("")
        self.lianxidianhua.setText("")
        self.label_9.setText(QCoreApplication.translate("Dialog", u"\u8054\u7cfb\u7535\u8bdd:", None))
        self.xingbie.setItemText(0, "")
        self.xingbie.setItemText(1, QCoreApplication.translate("Dialog", u"\u7537", None))
        self.xingbie.setItemText(2, QCoreApplication.translate("Dialog", u"\u5973", None))

        self.jinjilianxihaoma.setInputMask("")
        self.jinjilianxihaoma.setText("")
        self.label_10.setText(QCoreApplication.translate("Dialog", u"\u7d27\u6025\u8054\u7cfb\u7535\u8bdd:", None))
        self.jinjilianxiren.setInputMask("")
        self.jinjilianxiren.setText("")
        self.label_11.setText(QCoreApplication.translate("Dialog", u"\u7d27\u6025\u8054\u7cfb\u4eba:", None))
        self.chushengriqi.setInputMask("")
        self.chushengriqi.setText("")
        self.label_13.setText(QCoreApplication.translate("Dialog", u"\u51fa\u751f\u65e5\u671f:", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"\u8eab\u4efd\u8bc1\u53f7\u7801\uff1a", None))
        self.shenfenzhenghaoma.setInputMask("")
        self.shenfenzhenghaoma.setText("")
        self.dizhi.setInputMask("")
        self.dizhi.setText("")
        self.label_16.setText(QCoreApplication.translate("Dialog", u"\u5730\u5740:", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"\u5de5\u4f5c\u5e74\u4efd:", None))
        self.gongzuonianfen.setInputMask("")
        self.gongzuonianfen.setText("")
        self.tiaoxinriqi.setInputMask("")
        self.tiaoxinriqi.setText("")
        self.label_15.setText(QCoreApplication.translate("Dialog", u"\u8c03\u85aa\u65e5\u671f:", None))
        self.label_17.setText(QCoreApplication.translate("Dialog", u"\u5907\u6ce8:", None))
        self.beizhu.setInputMask("")
        self.beizhu.setText("")
        self.queren.setText(QCoreApplication.translate("Dialog", u"\u786e\u8ba4", None))
        self.chongzhi.setText(QCoreApplication.translate("Dialog", u"\u91cd\u7f6e", None))
        self.paizhao.setText(QCoreApplication.translate("Dialog", u"\u62cd\u7167", None))
        self.dakaixiangji.setText(QCoreApplication.translate("Dialog", u"\u6253\u5f00\u76f8\u673a", None))
        self.daiyu.setPrefix(QCoreApplication.translate("Dialog", u"$ ", None))
        self.lizhiriqi.setInputMask("")
        self.lizhiriqi.setText("")
        self.label_18.setText(QCoreApplication.translate("Dialog", u"\u5408\u540c\u65e5\u671f:", None))
        self.hetongriqi.setInputMask("")
        self.hetongriqi.setText("")
        self.label_19.setText(QCoreApplication.translate("Dialog", u"\u79bb\u804c\u65e5\u671f:", None))
    # retranslateUi

