# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '人员信息.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import res_rc

class Ui_renyuanxinxi(object):
    def setupUi(self, renyuanxinxi):
        if not renyuanxinxi.objectName():
            renyuanxinxi.setObjectName(u"renyuanxinxi")
        renyuanxinxi.setEnabled(True)
        renyuanxinxi.resize(1086, 823)
        renyuanxinxi.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"ICO/png/571417.png", QSize(), QIcon.Normal, QIcon.Off)
        renyuanxinxi.setWindowIcon(icon)
        renyuanxinxi.setDocumentMode(False)
        renyuanxinxi.setDockNestingEnabled(False)
        renyuanxinxi.setUnifiedTitleAndToolBarOnMac(False)
        self.action_xinzeng = QAction(renyuanxinxi)
        self.action_xinzeng.setObjectName(u"action_xinzeng")
        icon1 = QIcon()
        icon1.addFile(u":/new/prefix1/ICO/png/1081676.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_xinzeng.setIcon(icon1)
        self.action_shanchu = QAction(renyuanxinxi)
        self.action_shanchu.setObjectName(u"action_shanchu")
        icon2 = QIcon()
        icon2.addFile(u":/new/prefix1/ICO/png/1081640.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_shanchu.setIcon(icon2)
        self.action_xiugai = QAction(renyuanxinxi)
        self.action_xiugai.setObjectName(u"action_xiugai")
        icon3 = QIcon()
        icon3.addFile(u":/new/prefix1/ICO/png/1073170.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_xiugai.setIcon(icon3)
        self.action_chakan = QAction(renyuanxinxi)
        self.action_chakan.setObjectName(u"action_chakan")
        icon4 = QIcon()
        icon4.addFile(u":/new/prefix1/ICO/png/1081662.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_chakan.setIcon(icon4)
        self.action_daochu = QAction(renyuanxinxi)
        self.action_daochu.setObjectName(u"action_daochu")
        icon5 = QIcon()
        icon5.addFile(u":/new/prefix1/ICO/png/1081656.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_daochu.setIcon(icon5)
        self.action_liuchengtiaozhuan = QAction(renyuanxinxi)
        self.action_liuchengtiaozhuan.setObjectName(u"action_liuchengtiaozhuan")
        icon6 = QIcon()
        icon6.addFile(u":/new/prefix1/ICO/png/1081628.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_liuchengtiaozhuan.setIcon(icon6)
        self.action_chaxun = QAction(renyuanxinxi)
        self.action_chaxun.setObjectName(u"action_chaxun")
        icon7 = QIcon()
        icon7.addFile(u":/new/prefix1/ICO/png/1168148.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_chaxun.setIcon(icon7)
        self.action_tuichu = QAction(renyuanxinxi)
        self.action_tuichu.setObjectName(u"action_tuichu")
        icon8 = QIcon()
        icon8.addFile(u"ICO/png/1110305.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_tuichu.setIcon(icon8)
        self.action_biaotoushezhi = QAction(renyuanxinxi)
        self.action_biaotoushezhi.setObjectName(u"action_biaotoushezhi")
        icon9 = QIcon()
        icon9.addFile(u":/new/prefix1/ICO/png/1187149.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_biaotoushezhi.setIcon(icon9)
        self.action_liuchengshezhi = QAction(renyuanxinxi)
        self.action_liuchengshezhi.setObjectName(u"action_liuchengshezhi")
        icon10 = QIcon()
        icon10.addFile(u":/new/prefix1/ICO/png/1081680.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_liuchengshezhi.setIcon(icon10)
        self.centralwidget = QWidget(renyuanxinxi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMaximumSize(QSize(16777215, 40))
        self.Text_GongHao = QLineEdit(self.groupBox)
        self.Text_GongHao.setObjectName(u"Text_GongHao")
        self.Text_GongHao.setGeometry(QRect(190, 10, 81, 20))
        self.Text_GongHao.setMinimumSize(QSize(81, 20))
        self.Text_GongHao.setMaximumSize(QSize(81, 20))
        self.Text_XingMing = QLineEdit(self.groupBox)
        self.Text_XingMing.setObjectName(u"Text_XingMing")
        self.Text_XingMing.setGeometry(QRect(320, 10, 81, 20))
        self.Text_XingMing.setMinimumSize(QSize(81, 20))
        self.Text_XingMing.setMaximumSize(QSize(81, 20))
        self.Text_XingMing.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(555, 11, 31, 16))
        self.label_5.setMaximumSize(QSize(36, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(9, 11, 31, 16))
        self.label_2.setMaximumSize(QSize(36, 16))
        self.label_2.setStyleSheet(u"")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(160, 11, 31, 16))
        self.label_3.setMaximumSize(QSize(36, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(290, 11, 31, 16))
        self.label_4.setMaximumSize(QSize(36, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(680, 10, 16, 16))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(410, 10, 60, 20))
        self.label_13.setMaximumSize(QSize(60, 20))
        self.Text_ShaiXuan = QComboBox(self.groupBox)
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.setObjectName(u"Text_ShaiXuan")
        self.Text_ShaiXuan.setGeometry(QRect(470, 10, 81, 22))
        self.Text_BuMen = QComboBox(self.groupBox)
        self.Text_BuMen.setObjectName(u"Text_BuMen")
        self.Text_BuMen.setGeometry(QRect(40, 10, 111, 20))
        self.Text_BuMen.setMaximumSize(QSize(800, 20))
        self.Text_BuMen.setEditable(True)
        self.Text_BianJi = QTextEdit(self.groupBox)
        self.Text_BianJi.setObjectName(u"Text_BianJi")
        self.Text_BianJi.setGeometry(QRect(790, 5, 291, 31))
        self.Text_QiShi_RiQi = QLineEdit(self.groupBox)
        self.Text_QiShi_RiQi.setObjectName(u"Text_QiShi_RiQi")
        self.Text_QiShi_RiQi.setGeometry(QRect(585, 10, 91, 21))
        self.Text_JieShu_RiQi = QLineEdit(self.groupBox)
        self.Text_JieShu_RiQi.setObjectName(u"Text_JieShu_RiQi")
        self.Text_JieShu_RiQi.setGeometry(QRect(695, 10, 91, 21))

        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.Text_ShuJuXianShi = QTableWidget(self.centralwidget)
        self.Text_ShuJuXianShi.setObjectName(u"Text_ShuJuXianShi")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_ShuJuXianShi.sizePolicy().hasHeightForWidth())
        self.Text_ShuJuXianShi.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(240, 240, 240, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        self.Text_ShuJuXianShi.setPalette(palette)
        self.Text_ShuJuXianShi.setAutoScroll(True)

        self.gridLayout.addWidget(self.Text_ShuJuXianShi, 1, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        renyuanxinxi.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(renyuanxinxi)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setAllowedAreas(Qt.AllToolBarAreas)
        self.toolBar.setOrientation(Qt.Horizontal)
        self.toolBar.setIconSize(QSize(35, 35))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        renyuanxinxi.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.Text_BuMen, self.Text_GongHao)
        QWidget.setTabOrder(self.Text_GongHao, self.Text_XingMing)
        QWidget.setTabOrder(self.Text_XingMing, self.Text_ShaiXuan)
        QWidget.setTabOrder(self.Text_ShaiXuan, self.Text_QiShi_RiQi)
        QWidget.setTabOrder(self.Text_QiShi_RiQi, self.Text_JieShu_RiQi)
        QWidget.setTabOrder(self.Text_JieShu_RiQi, self.Text_BianJi)
        QWidget.setTabOrder(self.Text_BianJi, self.Text_ShuJuXianShi)

        self.toolBar.addAction(self.action_xinzeng)
        self.toolBar.addAction(self.action_shanchu)
        self.toolBar.addAction(self.action_xiugai)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chakan)
        self.toolBar.addAction(self.action_daochu)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_biaotoushezhi)
        self.toolBar.addAction(self.action_liuchengshezhi)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_liuchengtiaozhuan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chaxun)

        self.retranslateUi(renyuanxinxi)

        QMetaObject.connectSlotsByName(renyuanxinxi)
    # setupUi

    def retranslateUi(self, renyuanxinxi):
        renyuanxinxi.setWindowTitle(QCoreApplication.translate("renyuanxinxi", u"\u4eba\u5458\u4fe1\u606f", None))
        self.action_xinzeng.setText(QCoreApplication.translate("renyuanxinxi", u"\u65b0\u589e", None))
#if QT_CONFIG(shortcut)
        self.action_xinzeng.setShortcut(QCoreApplication.translate("renyuanxinxi", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_shanchu.setText(QCoreApplication.translate("renyuanxinxi", u"\u5220\u9664", None))
        self.action_xiugai.setText(QCoreApplication.translate("renyuanxinxi", u"\u4fee\u6539", None))
        self.action_chakan.setText(QCoreApplication.translate("renyuanxinxi", u"\u67e5\u770b", None))
        self.action_daochu.setText(QCoreApplication.translate("renyuanxinxi", u"\u5bfc\u51fa", None))
        self.action_liuchengtiaozhuan.setText(QCoreApplication.translate("renyuanxinxi", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.action_chaxun.setText(QCoreApplication.translate("renyuanxinxi", u"\u67e5\u8be2", None))
#if QT_CONFIG(shortcut)
        self.action_chaxun.setShortcut(QCoreApplication.translate("renyuanxinxi", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.action_tuichu.setText(QCoreApplication.translate("renyuanxinxi", u"\u9000\u51fa", None))
        self.action_biaotoushezhi.setText(QCoreApplication.translate("renyuanxinxi", u"\u8868\u5934\u8bbe\u7f6e", None))
        self.action_liuchengshezhi.setText(QCoreApplication.translate("renyuanxinxi", u"\u6d41\u7a0b\u8bbe\u7f6e", None))
        self.groupBox.setTitle("")
        self.label_5.setText(QCoreApplication.translate("renyuanxinxi", u"\u65e5\u671f\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("renyuanxinxi", u"\u90e8\u95e8\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("renyuanxinxi", u"\u5de5\u53f7\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("renyuanxinxi", u"\u59d3\u540d\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("renyuanxinxi", u"\u81f3", None))
        self.label_13.setText(QCoreApplication.translate("renyuanxinxi", u"\u7b5b\u9009\u65b9\u5f0f\uff1a", None))
        self.Text_ShaiXuan.setItemText(0, QCoreApplication.translate("renyuanxinxi", u"\u5728\u804c\u4eba\u5458", None))
        self.Text_ShaiXuan.setItemText(1, QCoreApplication.translate("renyuanxinxi", u"\u5165\u804c\u65e5\u671f", None))
        self.Text_ShaiXuan.setItemText(2, QCoreApplication.translate("renyuanxinxi", u"\u751f\u65e5\u65e5\u671f", None))
        self.Text_ShaiXuan.setItemText(3, QCoreApplication.translate("renyuanxinxi", u"\u79bb\u804c\u4eba\u5458", None))

        self.toolBar.setWindowTitle(QCoreApplication.translate("renyuanxinxi", u"\u4eba\u5458\u4fe1\u606f", None))
    # retranslateUi

