# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '人员信息.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_renyuanxinxi(object):
    def setupUi(self, renyuanxinxi):
        renyuanxinxi.setObjectName("renyuanxinxi")
        renyuanxinxi.setEnabled(True)
        renyuanxinxi.resize(1086, 589)
        renyuanxinxi.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/png/571417.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        renyuanxinxi.setWindowIcon(icon)
        renyuanxinxi.setDocumentMode(False)
        renyuanxinxi.setDockNestingEnabled(False)
        renyuanxinxi.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(renyuanxinxi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Text_GongHao = QtWidgets.QLineEdit(self.groupBox)
        self.Text_GongHao.setGeometry(QtCore.QRect(190, 10, 81, 20))
        self.Text_GongHao.setMinimumSize(QtCore.QSize(81, 20))
        self.Text_GongHao.setMaximumSize(QtCore.QSize(81, 20))
        self.Text_GongHao.setObjectName("Text_GongHao")
        self.Text_XingMing = QtWidgets.QLineEdit(self.groupBox)
        self.Text_XingMing.setGeometry(QtCore.QRect(320, 10, 81, 20))
        self.Text_XingMing.setMinimumSize(QtCore.QSize(81, 20))
        self.Text_XingMing.setMaximumSize(QtCore.QSize(81, 20))
        self.Text_XingMing.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.Text_XingMing.setObjectName("Text_XingMing")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(555, 11, 31, 16))
        self.label_5.setMaximumSize(QtCore.QSize(36, 16))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_2.setMaximumSize(QtCore.QSize(36, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 11, 31, 16))
        self.label_3.setMaximumSize(QtCore.QSize(36, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(290, 11, 31, 16))
        self.label_4.setMaximumSize(QtCore.QSize(36, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(680, 10, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        self.label_13.setObjectName("label_13")
        self.Text_ShaiXuan = QtWidgets.QComboBox(self.groupBox)
        self.Text_ShaiXuan.setGeometry(QtCore.QRect(470, 10, 81, 22))
        self.Text_ShaiXuan.setObjectName("Text_ShaiXuan")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_ShaiXuan.addItem("")
        self.Text_BuMen = QtWidgets.QComboBox(self.groupBox)
        self.Text_BuMen.setGeometry(QtCore.QRect(40, 10, 111, 20))
        self.Text_BuMen.setMaximumSize(QtCore.QSize(800, 20))
        self.Text_BuMen.setEditable(True)
        self.Text_BuMen.setObjectName("Text_BuMen")
        self.Text_BianJi = QtWidgets.QTextEdit(self.groupBox)
        self.Text_BianJi.setGeometry(QtCore.QRect(790, 5, 291, 31))
        self.Text_BianJi.setObjectName("Text_BianJi")
        self.Text_QiShi_RiQi = QtWidgets.QLineEdit(self.groupBox)
        self.Text_QiShi_RiQi.setGeometry(QtCore.QRect(585, 10, 91, 21))
        self.Text_QiShi_RiQi.setObjectName("Text_QiShi_RiQi")
        self.Text_JieShu_RiQi = QtWidgets.QLineEdit(self.groupBox)
        self.Text_JieShu_RiQi.setGeometry(QtCore.QRect(695, 10, 91, 21))
        self.Text_JieShu_RiQi.setObjectName("Text_JieShu_RiQi")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.Text_ShuJuXianShi = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_ShuJuXianShi.sizePolicy().hasHeightForWidth())
        self.Text_ShuJuXianShi.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Text_ShuJuXianShi.setPalette(palette)
        self.Text_ShuJuXianShi.setAutoScroll(True)
        self.Text_ShuJuXianShi.setObjectName("Text_ShuJuXianShi")
        self.Text_ShuJuXianShi.setColumnCount(0)
        self.Text_ShuJuXianShi.setRowCount(0)
        self.gridLayout.addWidget(self.Text_ShuJuXianShi, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        renyuanxinxi.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(renyuanxinxi)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        renyuanxinxi.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_xinzeng = QtWidgets.QAction(renyuanxinxi)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/png/1081676.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_xinzeng.setIcon(icon1)
        self.action_xinzeng.setObjectName("action_xinzeng")
        self.action_shanchu = QtWidgets.QAction(renyuanxinxi)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ICO/png/1081640.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_shanchu.setIcon(icon2)
        self.action_shanchu.setObjectName("action_shanchu")
        self.action_xiugai = QtWidgets.QAction(renyuanxinxi)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/png/1073170.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_xiugai.setIcon(icon3)
        self.action_xiugai.setObjectName("action_xiugai")
        self.action_chakan = QtWidgets.QAction(renyuanxinxi)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/png/1081662.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_chakan.setIcon(icon4)
        self.action_chakan.setObjectName("action_chakan")
        self.action_daochu = QtWidgets.QAction(renyuanxinxi)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/png/1081656.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_daochu.setIcon(icon5)
        self.action_daochu.setObjectName("action_daochu")
        self.action_liuchengtiaozhuan = QtWidgets.QAction(renyuanxinxi)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/png/1081628.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_liuchengtiaozhuan.setIcon(icon6)
        self.action_liuchengtiaozhuan.setObjectName("action_liuchengtiaozhuan")
        self.action_chaxun = QtWidgets.QAction(renyuanxinxi)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/png/1168148.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_chaxun.setIcon(icon7)
        self.action_chaxun.setObjectName("action_chaxun")
        self.action_tuichu = QtWidgets.QAction(renyuanxinxi)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ICO/png/1110305.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_tuichu.setIcon(icon8)
        self.action_tuichu.setObjectName("action_tuichu")
        self.action_biaotoushezhi = QtWidgets.QAction(renyuanxinxi)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ICO/png/1187149.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_biaotoushezhi.setIcon(icon9)
        self.action_biaotoushezhi.setObjectName("action_biaotoushezhi")
        self.action_liuchengshezhi = QtWidgets.QAction(renyuanxinxi)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ICO/png/1081680.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_liuchengshezhi.setIcon(icon10)
        self.action_liuchengshezhi.setObjectName("action_liuchengshezhi")
        self.toolBar.addAction(self.action_xinzeng)
        self.toolBar.addAction(self.action_shanchu)
        self.toolBar.addAction(self.action_xiugai)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chakan)
        self.toolBar.addAction(self.action_daochu)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_biaotoushezhi)
        self.toolBar.addAction(self.action_liuchengshezhi)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_liuchengtiaozhuan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chaxun)

        self.retranslateUi(renyuanxinxi)
        QtCore.QMetaObject.connectSlotsByName(renyuanxinxi)
        renyuanxinxi.setTabOrder(self.Text_BuMen, self.Text_GongHao)
        renyuanxinxi.setTabOrder(self.Text_GongHao, self.Text_XingMing)
        renyuanxinxi.setTabOrder(self.Text_XingMing, self.Text_ShaiXuan)
        renyuanxinxi.setTabOrder(self.Text_ShaiXuan, self.Text_QiShi_RiQi)
        renyuanxinxi.setTabOrder(self.Text_QiShi_RiQi, self.Text_JieShu_RiQi)
        renyuanxinxi.setTabOrder(self.Text_JieShu_RiQi, self.Text_BianJi)
        renyuanxinxi.setTabOrder(self.Text_BianJi, self.Text_ShuJuXianShi)

    def retranslateUi(self, renyuanxinxi):
        _translate = QtCore.QCoreApplication.translate
        renyuanxinxi.setWindowTitle(_translate("renyuanxinxi", "人员信息"))
        self.label_5.setText(_translate("renyuanxinxi", "日期："))
        self.label_2.setText(_translate("renyuanxinxi", "部门："))
        self.label_3.setText(_translate("renyuanxinxi", "工号："))
        self.label_4.setText(_translate("renyuanxinxi", "姓名："))
        self.label_6.setText(_translate("renyuanxinxi", "至"))
        self.label_13.setText(_translate("renyuanxinxi", "筛选方式："))
        self.Text_ShaiXuan.setItemText(0, _translate("renyuanxinxi", "在职人员"))
        self.Text_ShaiXuan.setItemText(1, _translate("renyuanxinxi", "入职日期"))
        self.Text_ShaiXuan.setItemText(2, _translate("renyuanxinxi", "生日日期"))
        self.Text_ShaiXuan.setItemText(3, _translate("renyuanxinxi", "离职人员"))
        self.toolBar.setWindowTitle(_translate("renyuanxinxi", "人员信息"))
        self.action_xinzeng.setText(_translate("renyuanxinxi", "新增"))
        self.action_xinzeng.setShortcut(_translate("renyuanxinxi", "Ctrl+Q"))
        self.action_shanchu.setText(_translate("renyuanxinxi", "删除"))
        self.action_xiugai.setText(_translate("renyuanxinxi", "修改"))
        self.action_chakan.setText(_translate("renyuanxinxi", "查看"))
        self.action_daochu.setText(_translate("renyuanxinxi", "导出"))
        self.action_liuchengtiaozhuan.setText(_translate("renyuanxinxi", "流程跳转"))
        self.action_chaxun.setText(_translate("renyuanxinxi", "查询"))
        self.action_chaxun.setShortcut(_translate("renyuanxinxi", "Return"))
        self.action_tuichu.setText(_translate("renyuanxinxi", "退出"))
        self.action_biaotoushezhi.setText(_translate("renyuanxinxi", "表头设置"))
        self.action_liuchengshezhi.setText(_translate("renyuanxinxi", "流程设置"))
