# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '项目信息.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_xiangmuxinxi(object):
    def setupUi(self, xiangmuxinxi):
        if not xiangmuxinxi.objectName():
            xiangmuxinxi.setObjectName(u"xiangmuxinxi")
        xiangmuxinxi.setEnabled(True)
        xiangmuxinxi.resize(1218, 589)
        xiangmuxinxi.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u"ICO/png/571417.png", QSize(), QIcon.Normal, QIcon.Off)
        xiangmuxinxi.setWindowIcon(icon)
        xiangmuxinxi.setDocumentMode(False)
        xiangmuxinxi.setDockNestingEnabled(False)
        xiangmuxinxi.setUnifiedTitleAndToolBarOnMac(False)
        self.action_xinzeng = QAction(xiangmuxinxi)
        self.action_xinzeng.setObjectName(u"action_xinzeng")
        icon1 = QIcon()
        icon1.addFile(u"ICO/png/1081676.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_xinzeng.setIcon(icon1)
        self.action_shanchu = QAction(xiangmuxinxi)
        self.action_shanchu.setObjectName(u"action_shanchu")
        icon2 = QIcon()
        icon2.addFile(u"ICO/png/1081640.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_shanchu.setIcon(icon2)
        self.action_xiugai = QAction(xiangmuxinxi)
        self.action_xiugai.setObjectName(u"action_xiugai")
        icon3 = QIcon()
        icon3.addFile(u"ICO/png/1073170.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_xiugai.setIcon(icon3)
        self.action_chakan = QAction(xiangmuxinxi)
        self.action_chakan.setObjectName(u"action_chakan")
        icon4 = QIcon()
        icon4.addFile(u"ICO/png/1081662.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_chakan.setIcon(icon4)
        self.action_daochu = QAction(xiangmuxinxi)
        self.action_daochu.setObjectName(u"action_daochu")
        icon5 = QIcon()
        icon5.addFile(u"ICO/png/1081656.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_daochu.setIcon(icon5)
        self.action_liuchengtiaozhuan = QAction(xiangmuxinxi)
        self.action_liuchengtiaozhuan.setObjectName(u"action_liuchengtiaozhuan")
        icon6 = QIcon()
        icon6.addFile(u"ICO/png/1081628.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_liuchengtiaozhuan.setIcon(icon6)
        self.action_chaxun = QAction(xiangmuxinxi)
        self.action_chaxun.setObjectName(u"action_chaxun")
        icon7 = QIcon()
        icon7.addFile(u"ICO/png/1168148.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_chaxun.setIcon(icon7)
        self.action_tuichu = QAction(xiangmuxinxi)
        self.action_tuichu.setObjectName(u"action_tuichu")
        icon8 = QIcon()
        icon8.addFile(u"ICO/png/1110305.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_tuichu.setIcon(icon8)
        self.action_biaotoushezhi = QAction(xiangmuxinxi)
        self.action_biaotoushezhi.setObjectName(u"action_biaotoushezhi")
        icon9 = QIcon()
        icon9.addFile(u"ICO/png/1187149.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_biaotoushezhi.setIcon(icon9)
        self.action_liuchengshezhi = QAction(xiangmuxinxi)
        self.action_liuchengshezhi.setObjectName(u"action_liuchengshezhi")
        icon10 = QIcon()
        icon10.addFile(u"ICO/png/1081680.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_liuchengshezhi.setIcon(icon10)
        self.centralwidget = QWidget(xiangmuxinxi)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_2 = QGridLayout(self.centralwidget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Text_ShuJuXianShi = QTableWidget(self.centralwidget)
        self.Text_ShuJuXianShi.setObjectName(u"Text_ShuJuXianShi")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_ShuJuXianShi.sizePolicy().hasHeightForWidth())
        self.Text_ShuJuXianShi.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(240, 240, 240, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        self.Text_ShuJuXianShi.setPalette(palette)
        self.Text_ShuJuXianShi.setAutoScroll(True)

        self.gridLayout.addWidget(self.Text_ShuJuXianShi, 2, 0, 1, 1)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QSize(16777215, 40))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(750, 10, 31, 20))
        self.label_5.setMaximumSize(QSize(6666, 6666))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(875, 10, 16, 20))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(620, 10, 60, 20))
        self.label_13.setMaximumSize(QSize(60, 20))
        self.Text_BianJi = QTextEdit(self.groupBox)
        self.Text_BianJi.setObjectName(u"Text_BianJi")
        self.Text_BianJi.setGeometry(QRect(1090, 5, 291, 31))
        self.Text_QiShi_RiQi = QLineEdit(self.groupBox)
        self.Text_QiShi_RiQi.setObjectName(u"Text_QiShi_RiQi")
        self.Text_QiShi_RiQi.setGeometry(QRect(780, 9, 91, 22))
        self.Text_JieShu_RiQi = QLineEdit(self.groupBox)
        self.Text_JieShu_RiQi.setObjectName(u"Text_JieShu_RiQi")
        self.Text_JieShu_RiQi.setGeometry(QRect(890, 9, 91, 22))
        self.Text_DanDangRen = QComboBox(self.groupBox)
        self.Text_DanDangRen.setObjectName(u"Text_DanDangRen")
        self.Text_DanDangRen.setGeometry(QRect(520, 9, 81, 22))
        self.Text_DanDangRen.setEditable(True)
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(9, 10, 31, 20))
        self.label_14.setMaximumSize(QSize(36, 66666))
        self.label_14.setStyleSheet(u"")
        self.Text_KeHuBianHhao = QComboBox(self.groupBox)
        self.Text_KeHuBianHhao.setObjectName(u"Text_KeHuBianHhao")
        self.Text_KeHuBianHhao.setGeometry(QRect(305, 9, 111, 22))
        self.Text_KeHuBianHhao.setEditable(True)
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(120, 10, 55, 20))
        self.label_15.setMaximumSize(QSize(360, 36))
        self.Text_XiangMuBianHao = QComboBox(self.groupBox)
        self.Text_XiangMuBianHao.setObjectName(u"Text_XiangMuBianHao")
        self.Text_XiangMuBianHao.setGeometry(QRect(175, 10, 69, 22))
        self.Text_XiangMuBianHao.setEditable(True)
        self.label_20 = QLabel(self.groupBox)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(430, 9, 51, 20))
        self.label_20.setMaximumSize(QSize(60, 20))
        self.Text_DanDangBuMen = QComboBox(self.groupBox)
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.setObjectName(u"Text_DanDangBuMen")
        self.Text_DanDangBuMen.setGeometry(QRect(470, 9, 51, 22))
        self.Text_KeHu = QComboBox(self.groupBox)
        self.Text_KeHu.setObjectName(u"Text_KeHu")
        self.Text_KeHu.setGeometry(QRect(40, 9, 69, 22))
        self.Text_KeHu.setEditable(True)
        self.label_19 = QLabel(self.groupBox)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(250, 10, 61, 20))
        self.Text_shaixuan = QComboBox(self.groupBox)
        self.Text_shaixuan.addItem("")
        self.Text_shaixuan.addItem("")
        self.Text_shaixuan.addItem("")
        self.Text_shaixuan.setObjectName(u"Text_shaixuan")
        self.Text_shaixuan.setGeometry(QRect(680, 10, 51, 22))
        self.layoutWidget = QWidget(self.groupBox)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(990, 0, 97, 40))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.checkBox_3 = QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName(u"checkBox_3")

        self.verticalLayout.addWidget(self.checkBox_3)

        self.checkBox_4 = QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName(u"checkBox_4")

        self.verticalLayout.addWidget(self.checkBox_4)


        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)


        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        xiangmuxinxi.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(xiangmuxinxi)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setAllowedAreas(Qt.AllToolBarAreas)
        self.toolBar.setOrientation(Qt.Horizontal)
        self.toolBar.setIconSize(QSize(35, 35))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        xiangmuxinxi.addToolBar(Qt.TopToolBarArea, self.toolBar)
        QWidget.setTabOrder(self.Text_KeHu, self.Text_XiangMuBianHao)
        QWidget.setTabOrder(self.Text_XiangMuBianHao, self.Text_KeHuBianHhao)
        QWidget.setTabOrder(self.Text_KeHuBianHhao, self.Text_DanDangBuMen)
        QWidget.setTabOrder(self.Text_DanDangBuMen, self.Text_DanDangRen)
        QWidget.setTabOrder(self.Text_DanDangRen, self.Text_shaixuan)
        QWidget.setTabOrder(self.Text_shaixuan, self.Text_QiShi_RiQi)
        QWidget.setTabOrder(self.Text_QiShi_RiQi, self.Text_JieShu_RiQi)
        QWidget.setTabOrder(self.Text_JieShu_RiQi, self.Text_BianJi)
        QWidget.setTabOrder(self.Text_BianJi, self.Text_ShuJuXianShi)

        self.toolBar.addAction(self.action_xinzeng)
        self.toolBar.addAction(self.action_shanchu)
        self.toolBar.addAction(self.action_xiugai)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chakan)
        self.toolBar.addAction(self.action_daochu)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_biaotoushezhi)
        self.toolBar.addAction(self.action_liuchengshezhi)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_liuchengtiaozhuan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chaxun)

        self.retranslateUi(xiangmuxinxi)

        QMetaObject.connectSlotsByName(xiangmuxinxi)
    # setupUi

    def retranslateUi(self, xiangmuxinxi):
        xiangmuxinxi.setWindowTitle(QCoreApplication.translate("xiangmuxinxi", u"\u9879\u76ee\u4fe1\u606f", None))
        self.action_xinzeng.setText(QCoreApplication.translate("xiangmuxinxi", u"\u65b0\u589e", None))
#if QT_CONFIG(shortcut)
        self.action_xinzeng.setShortcut(QCoreApplication.translate("xiangmuxinxi", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_shanchu.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5220\u9664", None))
        self.action_xiugai.setText(QCoreApplication.translate("xiangmuxinxi", u"\u4fee\u6539", None))
        self.action_chakan.setText(QCoreApplication.translate("xiangmuxinxi", u"\u67e5\u770b", None))
        self.action_daochu.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5bfc\u51fa", None))
        self.action_liuchengtiaozhuan.setText(QCoreApplication.translate("xiangmuxinxi", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.action_chaxun.setText(QCoreApplication.translate("xiangmuxinxi", u"\u67e5\u8be2", None))
#if QT_CONFIG(shortcut)
        self.action_chaxun.setShortcut(QCoreApplication.translate("xiangmuxinxi", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.action_tuichu.setText(QCoreApplication.translate("xiangmuxinxi", u"\u9000\u51fa", None))
        self.action_biaotoushezhi.setText(QCoreApplication.translate("xiangmuxinxi", u"\u8868\u5934\u8bbe\u7f6e", None))
        self.action_liuchengshezhi.setText(QCoreApplication.translate("xiangmuxinxi", u"\u6d41\u7a0b\u8bbe\u7f6e", None))
        self.groupBox.setTitle("")
        self.label_5.setText(QCoreApplication.translate("xiangmuxinxi", u"\u65e5\u671f\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("xiangmuxinxi", u"\u81f3", None))
        self.label_13.setText(QCoreApplication.translate("xiangmuxinxi", u"\u7b5b\u9009\u65b9\u5f0f\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5ba2\u6237\uff1a", None))
        self.label_15.setText(QCoreApplication.translate("xiangmuxinxi", u"\u9879\u76ee\u7f16\u53f7\uff1a", None))
        self.label_20.setText(QCoreApplication.translate("xiangmuxinxi", u"\u62c5\u5f53\u4eba\uff1a", None))
        self.Text_DanDangBuMen.setItemText(0, QCoreApplication.translate("xiangmuxinxi", u"\u4e1a\u52a1", None))
        self.Text_DanDangBuMen.setItemText(1, QCoreApplication.translate("xiangmuxinxi", u"\u9879\u76ee", None))
        self.Text_DanDangBuMen.setItemText(2, QCoreApplication.translate("xiangmuxinxi", u"\u8bbe\u8ba1", None))
        self.Text_DanDangBuMen.setItemText(3, QCoreApplication.translate("xiangmuxinxi", u"\u94b3\u5de5", None))

        self.label_19.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5ba2\u6237\u7f16\u53f7\uff1a", None))
        self.Text_shaixuan.setItemText(0, QCoreApplication.translate("xiangmuxinxi", u"\u4e0b\u5355", None))
        self.Text_shaixuan.setItemText(1, QCoreApplication.translate("xiangmuxinxi", u"\u9996\u6837", None))
        self.Text_shaixuan.setItemText(2, QCoreApplication.translate("xiangmuxinxi", u"\u79fb\u6a21", None))

        self.checkBox_3.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5305\u62ec\u79fb\u6a21\u9879\u76ee", None))
        self.checkBox_4.setText(QCoreApplication.translate("xiangmuxinxi", u"\u5305\u62ec\u5386\u53f2\u8bb0\u5f55", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("xiangmuxinxi", u"\u4eba\u5458\u4fe1\u606f", None))
    # retranslateUi

