# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '项目信息.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_xiangmuxinxi(object):
    def setupUi(self, xiangmuxinxi):
        xiangmuxinxi.setObjectName("xiangmuxinxi")
        xiangmuxinxi.setEnabled(True)
        xiangmuxinxi.resize(1218, 589)
        xiangmuxinxi.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/png/571417.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        xiangmuxinxi.setWindowIcon(icon)
        xiangmuxinxi.setDocumentMode(False)
        xiangmuxinxi.setDockNestingEnabled(False)
        xiangmuxinxi.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(xiangmuxinxi)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Text_ShuJuXianShi = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_ShuJuXianShi.sizePolicy().hasHeightForWidth())
        self.Text_ShuJuXianShi.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Text_ShuJuXianShi.setPalette(palette)
        self.Text_ShuJuXianShi.setAutoScroll(True)
        self.Text_ShuJuXianShi.setObjectName("Text_ShuJuXianShi")
        self.Text_ShuJuXianShi.setColumnCount(0)
        self.Text_ShuJuXianShi.setRowCount(0)
        self.gridLayout.addWidget(self.Text_ShuJuXianShi, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(750, 10, 31, 20))
        self.label_5.setMaximumSize(QtCore.QSize(6666, 6666))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(875, 10, 16, 20))
        self.label_6.setObjectName("label_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(620, 10, 60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        self.label_13.setObjectName("label_13")
        self.Text_BianJi = QtWidgets.QTextEdit(self.groupBox)
        self.Text_BianJi.setGeometry(QtCore.QRect(1090, 5, 291, 31))
        self.Text_BianJi.setObjectName("Text_BianJi")
        self.Text_QiShi_RiQi = QtWidgets.QLineEdit(self.groupBox)
        self.Text_QiShi_RiQi.setGeometry(QtCore.QRect(780, 9, 91, 22))
        self.Text_QiShi_RiQi.setObjectName("Text_QiShi_RiQi")
        self.Text_JieShu_RiQi = QtWidgets.QLineEdit(self.groupBox)
        self.Text_JieShu_RiQi.setGeometry(QtCore.QRect(890, 9, 91, 22))
        self.Text_JieShu_RiQi.setObjectName("Text_JieShu_RiQi")
        self.Text_DanDangRen = QtWidgets.QComboBox(self.groupBox)
        self.Text_DanDangRen.setGeometry(QtCore.QRect(520, 9, 81, 22))
        self.Text_DanDangRen.setEditable(True)
        self.Text_DanDangRen.setObjectName("Text_DanDangRen")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(9, 10, 31, 20))
        self.label_14.setMaximumSize(QtCore.QSize(36, 66666))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.Text_KeHuBianHhao = QtWidgets.QComboBox(self.groupBox)
        self.Text_KeHuBianHhao.setGeometry(QtCore.QRect(305, 9, 111, 22))
        self.Text_KeHuBianHhao.setEditable(True)
        self.Text_KeHuBianHhao.setObjectName("Text_KeHuBianHhao")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(120, 10, 55, 20))
        self.label_15.setMaximumSize(QtCore.QSize(360, 36))
        self.label_15.setObjectName("label_15")
        self.Text_NeiBuBianHao = QtWidgets.QComboBox(self.groupBox)
        self.Text_NeiBuBianHao.setGeometry(QtCore.QRect(175, 10, 69, 22))
        self.Text_NeiBuBianHao.setEditable(True)
        self.Text_NeiBuBianHao.setObjectName("Text_NeiBuBianHao")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(430, 9, 51, 20))
        self.label_20.setMaximumSize(QtCore.QSize(60, 20))
        self.label_20.setObjectName("label_20")
        self.Text_DanDangBuMen = QtWidgets.QComboBox(self.groupBox)
        self.Text_DanDangBuMen.setGeometry(QtCore.QRect(470, 9, 51, 22))
        self.Text_DanDangBuMen.setObjectName("Text_DanDangBuMen")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_DanDangBuMen.addItem("")
        self.Text_KeHu = QtWidgets.QComboBox(self.groupBox)
        self.Text_KeHu.setGeometry(QtCore.QRect(40, 9, 69, 22))
        self.Text_KeHu.setEditable(True)
        self.Text_KeHu.setObjectName("Text_KeHu")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(250, 10, 61, 20))
        self.label_19.setObjectName("label_19")
        self.Text_shaixuan = QtWidgets.QComboBox(self.groupBox)
        self.Text_shaixuan.setGeometry(QtCore.QRect(680, 10, 51, 22))
        self.Text_shaixuan.setObjectName("Text_shaixuan")
        self.Text_shaixuan.addItem("")
        self.Text_shaixuan.addItem("")
        self.Text_shaixuan.addItem("")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(990, 0, 97, 40))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        xiangmuxinxi.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(xiangmuxinxi)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(35, 35))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        xiangmuxinxi.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_xinzeng = QtWidgets.QAction(xiangmuxinxi)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/png/1081676.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_xinzeng.setIcon(icon1)
        self.action_xinzeng.setObjectName("action_xinzeng")
        self.action_shanchu = QtWidgets.QAction(xiangmuxinxi)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ICO/png/1081640.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_shanchu.setIcon(icon2)
        self.action_shanchu.setObjectName("action_shanchu")
        self.action_xiugai = QtWidgets.QAction(xiangmuxinxi)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/png/1073170.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_xiugai.setIcon(icon3)
        self.action_xiugai.setObjectName("action_xiugai")
        self.action_chakan = QtWidgets.QAction(xiangmuxinxi)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/png/1081662.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_chakan.setIcon(icon4)
        self.action_chakan.setObjectName("action_chakan")
        self.action_daochu = QtWidgets.QAction(xiangmuxinxi)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/png/1081656.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_daochu.setIcon(icon5)
        self.action_daochu.setObjectName("action_daochu")
        self.action_liuchengtiaozhuan = QtWidgets.QAction(xiangmuxinxi)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/png/1081628.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_liuchengtiaozhuan.setIcon(icon6)
        self.action_liuchengtiaozhuan.setObjectName("action_liuchengtiaozhuan")
        self.action_chaxun = QtWidgets.QAction(xiangmuxinxi)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/png/1168148.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_chaxun.setIcon(icon7)
        self.action_chaxun.setObjectName("action_chaxun")
        self.action_tuichu = QtWidgets.QAction(xiangmuxinxi)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ICO/png/1110305.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_tuichu.setIcon(icon8)
        self.action_tuichu.setObjectName("action_tuichu")
        self.action_biaotoushezhi = QtWidgets.QAction(xiangmuxinxi)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ICO/png/1187149.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_biaotoushezhi.setIcon(icon9)
        self.action_biaotoushezhi.setObjectName("action_biaotoushezhi")
        self.action_liuchengshezhi = QtWidgets.QAction(xiangmuxinxi)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ICO/png/1081680.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_liuchengshezhi.setIcon(icon10)
        self.action_liuchengshezhi.setObjectName("action_liuchengshezhi")
        self.toolBar.addAction(self.action_xinzeng)
        self.toolBar.addAction(self.action_shanchu)
        self.toolBar.addAction(self.action_xiugai)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chakan)
        self.toolBar.addAction(self.action_daochu)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_biaotoushezhi)
        self.toolBar.addAction(self.action_liuchengshezhi)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_liuchengtiaozhuan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_chaxun)

        self.retranslateUi(xiangmuxinxi)
        QtCore.QMetaObject.connectSlotsByName(xiangmuxinxi)
        xiangmuxinxi.setTabOrder(self.Text_KeHu, self.Text_NeiBuBianHao)
        xiangmuxinxi.setTabOrder(self.Text_NeiBuBianHao, self.Text_KeHuBianHhao)
        xiangmuxinxi.setTabOrder(self.Text_KeHuBianHhao, self.Text_DanDangBuMen)
        xiangmuxinxi.setTabOrder(self.Text_DanDangBuMen, self.Text_DanDangRen)
        xiangmuxinxi.setTabOrder(self.Text_DanDangRen, self.Text_shaixuan)
        xiangmuxinxi.setTabOrder(self.Text_shaixuan, self.Text_QiShi_RiQi)
        xiangmuxinxi.setTabOrder(self.Text_QiShi_RiQi, self.Text_JieShu_RiQi)
        xiangmuxinxi.setTabOrder(self.Text_JieShu_RiQi, self.Text_BianJi)
        xiangmuxinxi.setTabOrder(self.Text_BianJi, self.Text_ShuJuXianShi)

    def retranslateUi(self, xiangmuxinxi):
        _translate = QtCore.QCoreApplication.translate
        xiangmuxinxi.setWindowTitle(_translate("xiangmuxinxi", "项目信息"))
        self.label_5.setText(_translate("xiangmuxinxi", "日期："))
        self.label_6.setText(_translate("xiangmuxinxi", "至"))
        self.label_13.setText(_translate("xiangmuxinxi", "筛选方式："))
        self.label_14.setText(_translate("xiangmuxinxi", "客户："))
        self.label_15.setText(_translate("xiangmuxinxi", "内部编号："))
        self.label_20.setText(_translate("xiangmuxinxi", "担当人："))
        self.Text_DanDangBuMen.setItemText(0, _translate("xiangmuxinxi", "业务"))
        self.Text_DanDangBuMen.setItemText(1, _translate("xiangmuxinxi", "项目"))
        self.Text_DanDangBuMen.setItemText(2, _translate("xiangmuxinxi", "设计"))
        self.Text_DanDangBuMen.setItemText(3, _translate("xiangmuxinxi", "钳工"))
        self.label_19.setText(_translate("xiangmuxinxi", "客户编号："))
        self.Text_shaixuan.setItemText(0, _translate("xiangmuxinxi", "下单"))
        self.Text_shaixuan.setItemText(1, _translate("xiangmuxinxi", "首样"))
        self.Text_shaixuan.setItemText(2, _translate("xiangmuxinxi", "移模"))
        self.checkBox_3.setText(_translate("xiangmuxinxi", "包括移模项目"))
        self.checkBox_4.setText(_translate("xiangmuxinxi", "包括历史记录"))
        self.toolBar.setWindowTitle(_translate("xiangmuxinxi", "人员信息"))
        self.action_xinzeng.setText(_translate("xiangmuxinxi", "新增"))
        self.action_xinzeng.setShortcut(_translate("xiangmuxinxi", "Ctrl+Q"))
        self.action_shanchu.setText(_translate("xiangmuxinxi", "删除"))
        self.action_xiugai.setText(_translate("xiangmuxinxi", "修改"))
        self.action_chakan.setText(_translate("xiangmuxinxi", "查看"))
        self.action_daochu.setText(_translate("xiangmuxinxi", "导出"))
        self.action_liuchengtiaozhuan.setText(_translate("xiangmuxinxi", "流程跳转"))
        self.action_chaxun.setText(_translate("xiangmuxinxi", "查询"))
        self.action_chaxun.setShortcut(_translate("xiangmuxinxi", "Return"))
        self.action_tuichu.setText(_translate("xiangmuxinxi", "退出"))
        self.action_biaotoushezhi.setText(_translate("xiangmuxinxi", "表头设置"))
        self.action_liuchengshezhi.setText(_translate("xiangmuxinxi", "流程设置"))
