# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '主界面.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1077, 683)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"ICO/\u4e3b\u9898.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.人员查询 = QAction(MainWindow)
        self.人员查询.setObjectName(u"\u4eba\u5458\u67e5\u8be2")
        icon1 = QIcon()
        icon1.addFile(u"ICO/ico/shell32.dll(267).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.人员查询.setIcon(icon1)
        self.加班记录 = QAction(MainWindow)
        self.加班记录.setObjectName(u"\u52a0\u73ed\u8bb0\u5f55")
        icon2 = QIcon()
        icon2.addFile(u"ICO/png/1218679.png", QSize(), QIcon.Normal, QIcon.Off)
        self.加班记录.setIcon(icon2)
        self.请假记录 = QAction(MainWindow)
        self.请假记录.setObjectName(u"\u8bf7\u5047\u8bb0\u5f55")
        icon3 = QIcon()
        icon3.addFile(u"ICO/\u56fe\u6807-07.png", QSize(), QIcon.Normal, QIcon.Off)
        self.请假记录.setIcon(icon3)
        self.考勤记录 = QAction(MainWindow)
        self.考勤记录.setObjectName(u"\u8003\u52e4\u8bb0\u5f55")
        self.后勤申请 = QAction(MainWindow)
        self.后勤申请.setObjectName(u"\u540e\u52e4\u7533\u8bf7")
        self.项目信息 = QAction(MainWindow)
        self.项目信息.setObjectName(u"\u9879\u76ee\u4fe1\u606f")
        self.项目计划 = QAction(MainWindow)
        self.项目计划.setObjectName(u"\u9879\u76ee\u8ba1\u5212")
        self.机台安排 = QAction(MainWindow)
        self.机台安排.setObjectName(u"\u673a\u53f0\u5b89\u6392")
        self.设备维修 = QAction(MainWindow)
        self.设备维修.setObjectName(u"\u8bbe\u5907\u7ef4\u4fee")
        self.产品信息 = QAction(MainWindow)
        self.产品信息.setObjectName(u"\u4ea7\u54c1\u4fe1\u606f")
        self.验模信息 = QAction(MainWindow)
        self.验模信息.setObjectName(u"\u9a8c\u6a21\u4fe1\u606f")
        self.检具管理 = QAction(MainWindow)
        self.检具管理.setObjectName(u"\u68c0\u5177\u7ba1\u7406")
        self.仪校管理 = QAction(MainWindow)
        self.仪校管理.setObjectName(u"\u4eea\u6821\u7ba1\u7406")
        self.品质异常 = QAction(MainWindow)
        self.品质异常.setObjectName(u"\u54c1\u8d28\u5f02\u5e38")
        self.交样信息 = QAction(MainWindow)
        self.交样信息.setObjectName(u"\u4ea4\u6837\u4fe1\u606f")
        self.工程资料 = QAction(MainWindow)
        self.工程资料.setObjectName(u"\u5de5\u7a0b\u8d44\u6599")
        self.详细清单 = QAction(MainWindow)
        self.详细清单.setObjectName(u"\u8be6\u7ec6\u6e05\u5355")
        self.入库管理 = QAction(MainWindow)
        self.入库管理.setObjectName(u"\u5165\u5e93\u7ba1\u7406")
        self.出库管理 = QAction(MainWindow)
        self.出库管理.setObjectName(u"\u51fa\u5e93\u7ba1\u7406")
        self.退货管理 = QAction(MainWindow)
        self.退货管理.setObjectName(u"\u9000\u8d27\u7ba1\u7406")
        self.借用管理 = QAction(MainWindow)
        self.借用管理.setObjectName(u"\u501f\u7528\u7ba1\u7406")
        self.库存管理 = QAction(MainWindow)
        self.库存管理.setObjectName(u"\u5e93\u5b58\u7ba1\u7406")
        self.报废清单 = QAction(MainWindow)
        self.报废清单.setObjectName(u"\u62a5\u5e9f\u6e05\u5355")
        self.采购申请 = QAction(MainWindow)
        self.采购申请.setObjectName(u"\u91c7\u8d2d\u7533\u8bf7")
        self.品质一览 = QAction(MainWindow)
        self.品质一览.setObjectName(u"\u54c1\u8d28\u4e00\u89c8")
        self.异常一览 = QAction(MainWindow)
        self.异常一览.setObjectName(u"\u5f02\u5e38\u4e00\u89c8")
        self.进度一览 = QAction(MainWindow)
        self.进度一览.setObjectName(u"\u8fdb\u5ea6\u4e00\u89c8")
        self.库存一览 = QAction(MainWindow)
        self.库存一览.setObjectName(u"\u5e93\u5b58\u4e00\u89c8")
        self.截图软件 = QAction(MainWindow)
        self.截图软件.setObjectName(u"\u622a\u56fe\u8f6f\u4ef6")
        icon4 = QIcon()
        icon4.addFile(u"ICO/ico/shell32.dll(3).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.截图软件.setIcon(icon4)
        self.翻译软件 = QAction(MainWindow)
        self.翻译软件.setObjectName(u"\u7ffb\u8bd1\u8f6f\u4ef6")
        icon5 = QIcon()
        icon5.addFile(u"ICO/ico/shell32.dll(243).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.翻译软件.setIcon(icon5)
        self.日历 = QAction(MainWindow)
        self.日历.setObjectName(u"\u65e5\u5386")
        icon6 = QIcon()
        icon6.addFile(u"ICO/png/1234864.png", QSize(), QIcon.Normal, QIcon.Off)
        self.日历.setIcon(icon6)
        self.密码修改 = QAction(MainWindow)
        self.密码修改.setObjectName(u"\u5bc6\u7801\u4fee\u6539")
        icon7 = QIcon()
        icon7.addFile(u"ICO/ico/shell32.dll(194).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.密码修改.setIcon(icon7)
        self.账号切换 = QAction(MainWindow)
        self.账号切换.setObjectName(u"\u8d26\u53f7\u5207\u6362")
        icon8 = QIcon()
        icon8.addFile(u"ICO/ico/shell32.dll(269).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.账号切换.setIcon(icon8)
        self.退出 = QAction(MainWindow)
        self.退出.setObjectName(u"\u9000\u51fa")
        icon9 = QIcon()
        icon9.addFile(u"ICO/ico/shell32.dll(240).ico", QSize(), QIcon.Normal, QIcon.Off)
        self.退出.setIcon(icon9)
        self.皮肤 = QAction(MainWindow)
        self.皮肤.setObjectName(u"\u76ae\u80a4")
        icon10 = QIcon()
        icon10.addFile(u"ICO/1142575.png", QSize(), QIcon.Normal, QIcon.Off)
        self.皮肤.setIcon(icon10)
        self.采购管理 = QAction(MainWindow)
        self.采购管理.setObjectName(u"\u91c7\u8d2d\u7ba1\u7406")
        self.外协管理 = QAction(MainWindow)
        self.外协管理.setObjectName(u"\u5916\u534f\u7ba1\u7406")
        self.报销申请 = QAction(MainWindow)
        self.报销申请.setObjectName(u"\u62a5\u9500\u7533\u8bf7")
        self.体系查询 = QAction(MainWindow)
        self.体系查询.setObjectName(u"\u4f53\u7cfb\u67e5\u8be2")
        self.体系修改 = QAction(MainWindow)
        self.体系修改.setObjectName(u"\u4f53\u7cfb\u4fee\u6539")
        self.actioncsdc = QAction(MainWindow)
        self.actioncsdc.setObjectName(u"actioncsdc")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(800, 505))
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.ZhuCaiDan = QTabWidget(self.centralwidget)
        self.ZhuCaiDan.setObjectName(u"ZhuCaiDan")
        self.ZhuCaiDan.setEnabled(True)
        self.ZhuCaiDan.setMouseTracking(True)
        self.ZhuCaiDan.setTabletTracking(True)
        self.ZhuCaiDan.setFocusPolicy(Qt.ClickFocus)
        self.ZhuCaiDan.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.ZhuCaiDan.setAcceptDrops(True)
        self.ZhuCaiDan.setToolTipDuration(-1)
        self.ZhuCaiDan.setAutoFillBackground(False)
        self.ZhuCaiDan.setStyleSheet(u"")
        self.ZhuCaiDan.setDocumentMode(False)
        self.ZhuCaiDan.setTabsClosable(True)
        self.ZhuCaiDan.setMovable(False)
        self.ZhuCaiDan.setTabBarAutoHide(False)
        self.ranwu = QWidget()
        self.ranwu.setObjectName(u"ranwu")
        self.ZhuCaiDan.addTab(self.ranwu, "")
        self.zhicaidan = QWidget()
        self.zhicaidan.setObjectName(u"zhicaidan")
        self.ZhuCaiDan.addTab(self.zhicaidan, "")
        self.renyuanxinxi = QWidget()
        self.renyuanxinxi.setObjectName(u"renyuanxinxi")
        self.verticalLayout = QVBoxLayout(self.renyuanxinxi)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.widget = QWidget(self.renyuanxinxi)
        self.widget.setObjectName(u"widget")
        self.widget.setMaximumSize(QSize(16777215, 62))
        self.layoutWidget = QWidget(self.widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(1, 1, 390, 60))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.toolButton_6 = QToolButton(self.layoutWidget)
        self.toolButton_6.setObjectName(u"toolButton_6")
        icon11 = QIcon()
        icon11.addFile(u"ICO/png/1110305.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_6.setIcon(icon11)
        self.toolButton_6.setIconSize(QSize(36, 36))
        self.toolButton_6.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_6, 0, 9, 1, 1)

        self.toolButton_4 = QToolButton(self.layoutWidget)
        self.toolButton_4.setObjectName(u"toolButton_4")
        icon12 = QIcon()
        icon12.addFile(u"ICO/png/1081662.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_4.setIcon(icon12)
        self.toolButton_4.setIconSize(QSize(36, 36))
        self.toolButton_4.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_4, 0, 4, 1, 1)

        self.toolButton_3 = QToolButton(self.layoutWidget)
        self.toolButton_3.setObjectName(u"toolButton_3")
        icon13 = QIcon()
        icon13.addFile(u"ICO/png/1073170.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_3.setIcon(icon13)
        self.toolButton_3.setIconSize(QSize(36, 36))
        self.toolButton_3.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_3, 0, 2, 1, 1)

        self.toolButton_8 = QToolButton(self.layoutWidget)
        self.toolButton_8.setObjectName(u"toolButton_8")
        icon14 = QIcon()
        icon14.addFile(u"ICO/png/1081628.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_8.setIcon(icon14)
        self.toolButton_8.setIconSize(QSize(36, 36))
        self.toolButton_8.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_8.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_8, 0, 7, 1, 1)

        self.toolButton_2 = QToolButton(self.layoutWidget)
        self.toolButton_2.setObjectName(u"toolButton_2")
        icon15 = QIcon()
        icon15.addFile(u"ICO/png/1081640.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_2.setIcon(icon15)
        self.toolButton_2.setIconSize(QSize(36, 36))
        self.toolButton_2.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_2, 0, 1, 1, 1)

        self.toolButton_5 = QToolButton(self.layoutWidget)
        self.toolButton_5.setObjectName(u"toolButton_5")
        icon16 = QIcon()
        icon16.addFile(u"ICO/png/1081656.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton_5.setIcon(icon16)
        self.toolButton_5.setIconSize(QSize(36, 36))
        self.toolButton_5.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton_5, 0, 5, 1, 1)

        self.line_2 = QFrame(self.layoutWidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line_2, 0, 6, 1, 1)

        self.toolButton = QToolButton(self.layoutWidget)
        self.toolButton.setObjectName(u"toolButton")
        icon17 = QIcon()
        icon17.addFile(u"ICO/png/1081676.png", QSize(), QIcon.Normal, QIcon.Off)
        self.toolButton.setIcon(icon17)
        self.toolButton.setIconSize(QSize(36, 36))
        self.toolButton.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)

        self.gridLayout.addWidget(self.toolButton, 0, 0, 1, 1)

        self.line = QFrame(self.layoutWidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line, 0, 8, 1, 1)

        self.line_3 = QFrame(self.layoutWidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line_3, 0, 3, 1, 1)


        self.verticalLayout.addWidget(self.widget)

        self.groupBox = QGroupBox(self.renyuanxinxi)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMaximumSize(QSize(16777215, 40))
        self.chaxun = QPushButton(self.groupBox)
        self.chaxun.setObjectName(u"chaxun")
        self.chaxun.setEnabled(True)
        self.chaxun.setGeometry(QRect(790, 9, 75, 23))
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(190, 10, 81, 20))
        self.lineEdit_2.setMinimumSize(QSize(81, 20))
        self.lineEdit_2.setMaximumSize(QSize(81, 20))
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(320, 10, 81, 20))
        self.lineEdit_3.setMinimumSize(QSize(81, 20))
        self.lineEdit_3.setMaximumSize(QSize(81, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(555, 11, 31, 16))
        self.label_5.setMaximumSize(QSize(36, 16))
        self.dateEdit_2 = QDateEdit(self.groupBox)
        self.dateEdit_2.setObjectName(u"dateEdit_2")
        self.dateEdit_2.setGeometry(QRect(697, 10, 88, 20))
        self.dateEdit_2.setMinimumSize(QSize(88, 20))
        self.dateEdit_2.setMaximumSize(QSize(88, 20))
        self.dateEdit_2.setCurrentSection(QDateTimeEdit.YearSection)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setDate(QDate(2020, 1, 1))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(9, 11, 31, 16))
        self.label_2.setMaximumSize(QSize(36, 16))
        self.label_2.setStyleSheet(u"")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(160, 11, 31, 16))
        self.label_3.setMaximumSize(QSize(36, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(290, 11, 31, 16))
        self.label_4.setMaximumSize(QSize(36, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(680, 10, 16, 16))
        self.dateEdit = QDateEdit(self.groupBox)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(587, 10, 88, 20))
        self.dateEdit.setMinimumSize(QSize(88, 20))
        self.dateEdit.setMaximumSize(QSize(88, 20))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QDate(2020, 1, 1))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(410, 10, 60, 20))
        self.label_13.setMaximumSize(QSize(60, 20))
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(470, 10, 81, 22))
        self.comboBox_8 = QComboBox(self.groupBox)
        self.comboBox_8.setObjectName(u"comboBox_8")
        self.comboBox_8.setGeometry(QRect(40, 10, 111, 20))
        self.comboBox_8.setMaximumSize(QSize(800, 20))
        self.comboBox_8.setEditable(True)

        self.verticalLayout.addWidget(self.groupBox)

        self.tableWidget = QTableWidget(self.renyuanxinxi)
        if (self.tableWidget.columnCount() < 16):
            self.tableWidget.setColumnCount(16)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, __qtablewidgetitem15)
        self.tableWidget.setObjectName(u"tableWidget")
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoScroll(True)

        self.verticalLayout.addWidget(self.tableWidget)

        self.ZhuCaiDan.addTab(self.renyuanxinxi, "")
        self.xiangmuxinxi = QWidget()
        self.xiangmuxinxi.setObjectName(u"xiangmuxinxi")
        self.verticalLayout_2 = QVBoxLayout(self.xiangmuxinxi)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.widget_2 = QWidget(self.xiangmuxinxi)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setMaximumSize(QSize(16777215, 62))
        self.layoutWidget1 = QWidget(self.widget_2)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(1, 1, 390, 60))
        self.gridLayout_2 = QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.toolButton_7 = QToolButton(self.layoutWidget1)
        self.toolButton_7.setObjectName(u"toolButton_7")
        self.toolButton_7.setIcon(icon11)
        self.toolButton_7.setIconSize(QSize(36, 36))
        self.toolButton_7.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_7.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_7, 0, 9, 1, 1)

        self.toolButton_9 = QToolButton(self.layoutWidget1)
        self.toolButton_9.setObjectName(u"toolButton_9")
        self.toolButton_9.setIcon(icon12)
        self.toolButton_9.setIconSize(QSize(36, 36))
        self.toolButton_9.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_9.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_9, 0, 4, 1, 1)

        self.toolButton_10 = QToolButton(self.layoutWidget1)
        self.toolButton_10.setObjectName(u"toolButton_10")
        self.toolButton_10.setIcon(icon13)
        self.toolButton_10.setIconSize(QSize(36, 36))
        self.toolButton_10.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_10.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_10, 0, 2, 1, 1)

        self.toolButton_11 = QToolButton(self.layoutWidget1)
        self.toolButton_11.setObjectName(u"toolButton_11")
        self.toolButton_11.setIcon(icon14)
        self.toolButton_11.setIconSize(QSize(36, 36))
        self.toolButton_11.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_11.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_11, 0, 7, 1, 1)

        self.toolButton_12 = QToolButton(self.layoutWidget1)
        self.toolButton_12.setObjectName(u"toolButton_12")
        self.toolButton_12.setIcon(icon15)
        self.toolButton_12.setIconSize(QSize(36, 36))
        self.toolButton_12.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_12.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_12, 0, 1, 1, 1)

        self.toolButton_13 = QToolButton(self.layoutWidget1)
        self.toolButton_13.setObjectName(u"toolButton_13")
        self.toolButton_13.setIcon(icon16)
        self.toolButton_13.setIconSize(QSize(36, 36))
        self.toolButton_13.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_13.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_13, 0, 5, 1, 1)

        self.line_4 = QFrame(self.layoutWidget1)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.gridLayout_2.addWidget(self.line_4, 0, 6, 1, 1)

        self.toolButton_14 = QToolButton(self.layoutWidget1)
        self.toolButton_14.setObjectName(u"toolButton_14")
        self.toolButton_14.setIcon(icon17)
        self.toolButton_14.setIconSize(QSize(36, 36))
        self.toolButton_14.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_14.setAutoRaise(True)

        self.gridLayout_2.addWidget(self.toolButton_14, 0, 0, 1, 1)

        self.line_5 = QFrame(self.layoutWidget1)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)

        self.gridLayout_2.addWidget(self.line_5, 0, 8, 1, 1)

        self.line_6 = QFrame(self.layoutWidget1)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)

        self.gridLayout_2.addWidget(self.line_6, 0, 3, 1, 1)


        self.verticalLayout_2.addWidget(self.widget_2)

        self.groupBox_3 = QGroupBox(self.xiangmuxinxi)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setMaximumSize(QSize(16777215, 40))
        self.chaxun_2 = QPushButton(self.groupBox_3)
        self.chaxun_2.setObjectName(u"chaxun_2")
        self.chaxun_2.setEnabled(True)
        self.chaxun_2.setGeometry(QRect(1090, 10, 75, 23))
        self.label_12 = QLabel(self.groupBox_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(755, 12, 31, 16))
        self.label_12.setMaximumSize(QSize(36, 16))
        self.dateEdit_3 = QDateEdit(self.groupBox_3)
        self.dateEdit_3.setObjectName(u"dateEdit_3")
        self.dateEdit_3.setGeometry(QRect(897, 11, 88, 20))
        self.dateEdit_3.setMinimumSize(QSize(88, 20))
        self.dateEdit_3.setMaximumSize(QSize(88, 20))
        self.dateEdit_3.setCalendarPopup(True)
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(9, 11, 31, 16))
        self.label_14.setMaximumSize(QSize(36, 16))
        self.label_14.setStyleSheet(u"")
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(120, 10, 31, 16))
        self.label_15.setMaximumSize(QSize(36, 16))
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(880, 11, 16, 16))
        self.dateEdit_4 = QDateEdit(self.groupBox_3)
        self.dateEdit_4.setObjectName(u"dateEdit_4")
        self.dateEdit_4.setGeometry(QRect(787, 11, 88, 20))
        self.dateEdit_4.setMinimumSize(QSize(88, 20))
        self.dateEdit_4.setMaximumSize(QSize(88, 20))
        self.dateEdit_4.setCalendarPopup(True)
        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(610, 10, 60, 20))
        self.label_18.setMaximumSize(QSize(60, 20))
        self.comboBox_2 = QComboBox(self.groupBox_3)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(460, 9, 51, 22))
        self.comboBox_3 = QComboBox(self.groupBox_3)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(40, 9, 69, 22))
        self.comboBox_3.setEditable(True)
        self.comboBox_4 = QComboBox(self.groupBox_3)
        self.comboBox_4.setObjectName(u"comboBox_4")
        self.comboBox_4.setGeometry(QRect(150, 9, 69, 22))
        self.comboBox_4.setEditable(True)
        self.comboBox_5 = QComboBox(self.groupBox_3)
        self.comboBox_5.setObjectName(u"comboBox_5")
        self.comboBox_5.setGeometry(QRect(290, 9, 111, 22))
        self.comboBox_5.setEditable(True)
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(230, 10, 61, 20))
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(420, 10, 51, 20))
        self.label_20.setMaximumSize(QSize(60, 20))
        self.comboBox_6 = QComboBox(self.groupBox_3)
        self.comboBox_6.setObjectName(u"comboBox_6")
        self.comboBox_6.setGeometry(QRect(510, 9, 81, 22))
        self.comboBox_6.setEditable(True)
        self.comboBox_7 = QComboBox(self.groupBox_3)
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.setObjectName(u"comboBox_7")
        self.comboBox_7.setGeometry(QRect(670, 10, 51, 22))
        self.checkBox_3 = QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(990, 2, 89, 16))
        self.checkBox_4 = QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(990, 20, 89, 16))

        self.verticalLayout_2.addWidget(self.groupBox_3)

        self.tableWidget_xm = QTableWidget(self.xiangmuxinxi)
        if (self.tableWidget_xm.columnCount() < 15):
            self.tableWidget_xm.setColumnCount(15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(1, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(2, __qtablewidgetitem18)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(3, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(4, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(5, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(6, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(7, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(8, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(9, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(10, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(11, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(12, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(13, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidget_xm.setHorizontalHeaderItem(14, __qtablewidgetitem30)
        self.tableWidget_xm.setObjectName(u"tableWidget_xm")
        sizePolicy.setHeightForWidth(self.tableWidget_xm.sizePolicy().hasHeightForWidth())
        self.tableWidget_xm.setSizePolicy(sizePolicy)
        self.tableWidget_xm.setAutoScroll(True)

        self.verticalLayout_2.addWidget(self.tableWidget_xm)

        self.ZhuCaiDan.addTab(self.xiangmuxinxi, "")
        self.jiancebaogao = QWidget()
        self.jiancebaogao.setObjectName(u"jiancebaogao")
        self.verticalLayout_3 = QVBoxLayout(self.jiancebaogao)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.widget_3 = QWidget(self.jiancebaogao)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMaximumSize(QSize(16777215, 62))
        self.layoutWidget_2 = QWidget(self.widget_3)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(1, 1, 390, 60))
        self.gridLayout_4 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.toolButton_15 = QToolButton(self.layoutWidget_2)
        self.toolButton_15.setObjectName(u"toolButton_15")
        self.toolButton_15.setIcon(icon11)
        self.toolButton_15.setIconSize(QSize(36, 36))
        self.toolButton_15.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_15.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_15, 0, 9, 1, 1)

        self.toolButton_16 = QToolButton(self.layoutWidget_2)
        self.toolButton_16.setObjectName(u"toolButton_16")
        self.toolButton_16.setIcon(icon12)
        self.toolButton_16.setIconSize(QSize(36, 36))
        self.toolButton_16.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_16.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_16, 0, 4, 1, 1)

        self.toolButton_17 = QToolButton(self.layoutWidget_2)
        self.toolButton_17.setObjectName(u"toolButton_17")
        self.toolButton_17.setIcon(icon13)
        self.toolButton_17.setIconSize(QSize(36, 36))
        self.toolButton_17.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_17.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_17, 0, 2, 1, 1)

        self.toolButton_18 = QToolButton(self.layoutWidget_2)
        self.toolButton_18.setObjectName(u"toolButton_18")
        self.toolButton_18.setIcon(icon14)
        self.toolButton_18.setIconSize(QSize(36, 36))
        self.toolButton_18.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_18.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_18, 0, 7, 1, 1)

        self.toolButton_19 = QToolButton(self.layoutWidget_2)
        self.toolButton_19.setObjectName(u"toolButton_19")
        self.toolButton_19.setIcon(icon15)
        self.toolButton_19.setIconSize(QSize(36, 36))
        self.toolButton_19.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_19.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_19, 0, 1, 1, 1)

        self.toolButton_20 = QToolButton(self.layoutWidget_2)
        self.toolButton_20.setObjectName(u"toolButton_20")
        self.toolButton_20.setIcon(icon16)
        self.toolButton_20.setIconSize(QSize(36, 36))
        self.toolButton_20.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_20.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_20, 0, 5, 1, 1)

        self.line_7 = QFrame(self.layoutWidget_2)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line_7, 0, 6, 1, 1)

        self.toolButton_21 = QToolButton(self.layoutWidget_2)
        self.toolButton_21.setObjectName(u"toolButton_21")
        self.toolButton_21.setIcon(icon17)
        self.toolButton_21.setIconSize(QSize(36, 36))
        self.toolButton_21.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_21.setAutoRaise(True)

        self.gridLayout_4.addWidget(self.toolButton_21, 0, 0, 1, 1)

        self.line_8 = QFrame(self.layoutWidget_2)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line_8, 0, 8, 1, 1)

        self.line_9 = QFrame(self.layoutWidget_2)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setFrameShape(QFrame.VLine)
        self.line_9.setFrameShadow(QFrame.Sunken)

        self.gridLayout_4.addWidget(self.line_9, 0, 3, 1, 1)


        self.verticalLayout_3.addWidget(self.widget_3)

        self.groupBox_4 = QGroupBox(self.jiancebaogao)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setMaximumSize(QSize(16777215, 40))
        self.chaxun_3 = QPushButton(self.groupBox_4)
        self.chaxun_3.setObjectName(u"chaxun_3")
        self.chaxun_3.setEnabled(True)
        self.chaxun_3.setGeometry(QRect(1020, 10, 75, 23))
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(685, 12, 31, 16))
        self.label_16.setMaximumSize(QSize(36, 16))
        self.dateEdit_5 = QDateEdit(self.groupBox_4)
        self.dateEdit_5.setObjectName(u"dateEdit_5")
        self.dateEdit_5.setGeometry(QRect(827, 11, 88, 20))
        self.dateEdit_5.setMinimumSize(QSize(88, 20))
        self.dateEdit_5.setMaximumSize(QSize(88, 20))
        self.dateEdit_5.setCalendarPopup(True)
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(9, 11, 31, 16))
        self.label_21.setMaximumSize(QSize(36, 16))
        self.label_21.setStyleSheet(u"")
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(120, 10, 31, 16))
        self.label_22.setMaximumSize(QSize(36, 16))
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(810, 11, 16, 16))
        self.dateEdit_6 = QDateEdit(self.groupBox_4)
        self.dateEdit_6.setObjectName(u"dateEdit_6")
        self.dateEdit_6.setGeometry(QRect(717, 11, 88, 20))
        self.dateEdit_6.setMinimumSize(QSize(88, 20))
        self.dateEdit_6.setMaximumSize(QSize(88, 20))
        self.dateEdit_6.setCalendarPopup(True)
        self.comboBox_10 = QComboBox(self.groupBox_4)
        self.comboBox_10.setObjectName(u"comboBox_10")
        self.comboBox_10.setGeometry(QRect(40, 9, 69, 22))
        self.comboBox_10.setEditable(True)
        self.comboBox_11 = QComboBox(self.groupBox_4)
        self.comboBox_11.setObjectName(u"comboBox_11")
        self.comboBox_11.setGeometry(QRect(150, 9, 69, 22))
        self.comboBox_11.setEditable(True)
        self.comboBox_12 = QComboBox(self.groupBox_4)
        self.comboBox_12.setObjectName(u"comboBox_12")
        self.comboBox_12.setGeometry(QRect(290, 9, 111, 22))
        self.comboBox_12.setEditable(True)
        self.label_25 = QLabel(self.groupBox_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(230, 10, 61, 20))
        self.checkBox_5 = QCheckBox(self.groupBox_4)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(920, 2, 89, 16))
        self.checkBox_6 = QCheckBox(self.groupBox_4)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(920, 20, 89, 16))
        self.comboBox_18 = QComboBox(self.groupBox_4)
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.setObjectName(u"comboBox_18")
        self.comboBox_18.setGeometry(QRect(450, 10, 51, 22))
        self.label_33 = QLabel(self.groupBox_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(420, 10, 31, 20))
        self.label_33.setMaximumSize(QSize(60, 20))
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(520, 10, 60, 20))
        self.label_31.setMaximumSize(QSize(60, 20))
        self.lineEdit_8 = QLineEdit(self.groupBox_4)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(580, 10, 81, 20))
        self.lineEdit_8.setMinimumSize(QSize(81, 20))
        self.lineEdit_8.setMaximumSize(QSize(81, 20))
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setClearButtonEnabled(False)

        self.verticalLayout_3.addWidget(self.groupBox_4)

        self.tableWidget_jc = QTableWidget(self.jiancebaogao)
        if (self.tableWidget_jc.columnCount() < 16):
            self.tableWidget_jc.setColumnCount(16)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(0, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(1, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(2, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(3, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(4, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(5, __qtablewidgetitem36)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(6, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(7, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(8, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(9, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(10, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(11, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(12, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(13, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(14, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.tableWidget_jc.setHorizontalHeaderItem(15, __qtablewidgetitem46)
        self.tableWidget_jc.setObjectName(u"tableWidget_jc")
        sizePolicy.setHeightForWidth(self.tableWidget_jc.sizePolicy().hasHeightForWidth())
        self.tableWidget_jc.setSizePolicy(sizePolicy)
        self.tableWidget_jc.setAutoScroll(True)

        self.verticalLayout_3.addWidget(self.tableWidget_jc)

        self.ZhuCaiDan.addTab(self.jiancebaogao, "")
        self.yanmoxingxi = QWidget()
        self.yanmoxingxi.setObjectName(u"yanmoxingxi")
        self.verticalLayout_4 = QVBoxLayout(self.yanmoxingxi)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.widget_4 = QWidget(self.yanmoxingxi)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setMaximumSize(QSize(16777215, 62))
        self.layoutWidget_3 = QWidget(self.widget_4)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(1, 1, 390, 60))
        self.gridLayout_5 = QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.toolButton_22 = QToolButton(self.layoutWidget_3)
        self.toolButton_22.setObjectName(u"toolButton_22")
        self.toolButton_22.setIcon(icon11)
        self.toolButton_22.setIconSize(QSize(36, 36))
        self.toolButton_22.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_22.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_22, 0, 9, 1, 1)

        self.toolButton_23 = QToolButton(self.layoutWidget_3)
        self.toolButton_23.setObjectName(u"toolButton_23")
        self.toolButton_23.setIcon(icon12)
        self.toolButton_23.setIconSize(QSize(36, 36))
        self.toolButton_23.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_23.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_23, 0, 4, 1, 1)

        self.toolButton_24 = QToolButton(self.layoutWidget_3)
        self.toolButton_24.setObjectName(u"toolButton_24")
        self.toolButton_24.setIcon(icon13)
        self.toolButton_24.setIconSize(QSize(36, 36))
        self.toolButton_24.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_24.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_24, 0, 2, 1, 1)

        self.toolButton_25 = QToolButton(self.layoutWidget_3)
        self.toolButton_25.setObjectName(u"toolButton_25")
        self.toolButton_25.setIcon(icon14)
        self.toolButton_25.setIconSize(QSize(36, 36))
        self.toolButton_25.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_25.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_25, 0, 7, 1, 1)

        self.toolButton_26 = QToolButton(self.layoutWidget_3)
        self.toolButton_26.setObjectName(u"toolButton_26")
        self.toolButton_26.setIcon(icon15)
        self.toolButton_26.setIconSize(QSize(36, 36))
        self.toolButton_26.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_26.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_26, 0, 1, 1, 1)

        self.toolButton_27 = QToolButton(self.layoutWidget_3)
        self.toolButton_27.setObjectName(u"toolButton_27")
        self.toolButton_27.setIcon(icon16)
        self.toolButton_27.setIconSize(QSize(36, 36))
        self.toolButton_27.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_27.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_27, 0, 5, 1, 1)

        self.line_10 = QFrame(self.layoutWidget_3)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)

        self.gridLayout_5.addWidget(self.line_10, 0, 6, 1, 1)

        self.toolButton_28 = QToolButton(self.layoutWidget_3)
        self.toolButton_28.setObjectName(u"toolButton_28")
        self.toolButton_28.setIcon(icon17)
        self.toolButton_28.setIconSize(QSize(36, 36))
        self.toolButton_28.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.toolButton_28.setAutoRaise(True)

        self.gridLayout_5.addWidget(self.toolButton_28, 0, 0, 1, 1)

        self.line_11 = QFrame(self.layoutWidget_3)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setFrameShape(QFrame.VLine)
        self.line_11.setFrameShadow(QFrame.Sunken)

        self.gridLayout_5.addWidget(self.line_11, 0, 8, 1, 1)

        self.line_12 = QFrame(self.layoutWidget_3)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setFrameShape(QFrame.VLine)
        self.line_12.setFrameShadow(QFrame.Sunken)

        self.gridLayout_5.addWidget(self.line_12, 0, 3, 1, 1)


        self.verticalLayout_4.addWidget(self.widget_4)

        self.groupBox_5 = QGroupBox(self.yanmoxingxi)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setMaximumSize(QSize(16777215, 40))
        self.chaxun_4 = QPushButton(self.groupBox_5)
        self.chaxun_4.setObjectName(u"chaxun_4")
        self.chaxun_4.setEnabled(True)
        self.chaxun_4.setGeometry(QRect(920, 10, 75, 23))
        self.label_24 = QLabel(self.groupBox_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(585, 12, 31, 16))
        self.label_24.setMaximumSize(QSize(36, 16))
        self.dateEdit_7 = QDateEdit(self.groupBox_5)
        self.dateEdit_7.setObjectName(u"dateEdit_7")
        self.dateEdit_7.setGeometry(QRect(727, 11, 88, 20))
        self.dateEdit_7.setMinimumSize(QSize(88, 20))
        self.dateEdit_7.setMaximumSize(QSize(88, 20))
        self.dateEdit_7.setCalendarPopup(True)
        self.label_26 = QLabel(self.groupBox_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(9, 11, 31, 16))
        self.label_26.setMaximumSize(QSize(36, 16))
        self.label_26.setStyleSheet(u"")
        self.label_27 = QLabel(self.groupBox_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(120, 10, 31, 16))
        self.label_27.setMaximumSize(QSize(36, 16))
        self.label_28 = QLabel(self.groupBox_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(710, 11, 16, 16))
        self.dateEdit_8 = QDateEdit(self.groupBox_5)
        self.dateEdit_8.setObjectName(u"dateEdit_8")
        self.dateEdit_8.setGeometry(QRect(617, 11, 88, 20))
        self.dateEdit_8.setMinimumSize(QSize(88, 20))
        self.dateEdit_8.setMaximumSize(QSize(88, 20))
        self.dateEdit_8.setCalendarPopup(True)
        self.comboBox_13 = QComboBox(self.groupBox_5)
        self.comboBox_13.setObjectName(u"comboBox_13")
        self.comboBox_13.setGeometry(QRect(40, 9, 69, 22))
        self.comboBox_13.setEditable(True)
        self.comboBox_14 = QComboBox(self.groupBox_5)
        self.comboBox_14.setObjectName(u"comboBox_14")
        self.comboBox_14.setGeometry(QRect(150, 9, 69, 22))
        self.comboBox_14.setEditable(True)
        self.comboBox_15 = QComboBox(self.groupBox_5)
        self.comboBox_15.setObjectName(u"comboBox_15")
        self.comboBox_15.setGeometry(QRect(290, 9, 111, 22))
        self.comboBox_15.setEditable(True)
        self.label_29 = QLabel(self.groupBox_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(230, 10, 61, 20))
        self.checkBox_7 = QCheckBox(self.groupBox_5)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(820, 2, 89, 16))
        self.checkBox_8 = QCheckBox(self.groupBox_5)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(820, 20, 89, 16))
        self.label_38 = QLabel(self.groupBox_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(420, 10, 60, 20))
        self.label_38.setMaximumSize(QSize(60, 20))
        self.lineEdit_10 = QLineEdit(self.groupBox_5)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(480, 10, 81, 20))
        self.lineEdit_10.setMinimumSize(QSize(81, 20))
        self.lineEdit_10.setMaximumSize(QSize(81, 20))

        self.verticalLayout_4.addWidget(self.groupBox_5)

        self.tableWidget_ym = QTableWidget(self.yanmoxingxi)
        if (self.tableWidget_ym.columnCount() < 21):
            self.tableWidget_ym.setColumnCount(21)
        __qtablewidgetitem47 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(0, __qtablewidgetitem47)
        __qtablewidgetitem48 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(1, __qtablewidgetitem48)
        __qtablewidgetitem49 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(2, __qtablewidgetitem49)
        __qtablewidgetitem50 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(3, __qtablewidgetitem50)
        __qtablewidgetitem51 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(4, __qtablewidgetitem51)
        __qtablewidgetitem52 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(5, __qtablewidgetitem52)
        __qtablewidgetitem53 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(6, __qtablewidgetitem53)
        __qtablewidgetitem54 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(7, __qtablewidgetitem54)
        __qtablewidgetitem55 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(8, __qtablewidgetitem55)
        __qtablewidgetitem56 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(9, __qtablewidgetitem56)
        __qtablewidgetitem57 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(10, __qtablewidgetitem57)
        __qtablewidgetitem58 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(11, __qtablewidgetitem58)
        __qtablewidgetitem59 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(12, __qtablewidgetitem59)
        __qtablewidgetitem60 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(13, __qtablewidgetitem60)
        __qtablewidgetitem61 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(14, __qtablewidgetitem61)
        __qtablewidgetitem62 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(15, __qtablewidgetitem62)
        __qtablewidgetitem63 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(16, __qtablewidgetitem63)
        __qtablewidgetitem64 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(17, __qtablewidgetitem64)
        __qtablewidgetitem65 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(18, __qtablewidgetitem65)
        __qtablewidgetitem66 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(19, __qtablewidgetitem66)
        __qtablewidgetitem67 = QTableWidgetItem()
        self.tableWidget_ym.setHorizontalHeaderItem(20, __qtablewidgetitem67)
        self.tableWidget_ym.setObjectName(u"tableWidget_ym")
        sizePolicy.setHeightForWidth(self.tableWidget_ym.sizePolicy().hasHeightForWidth())
        self.tableWidget_ym.setSizePolicy(sizePolicy)
        self.tableWidget_ym.setAutoScroll(True)

        self.verticalLayout_4.addWidget(self.tableWidget_ym)

        self.ZhuCaiDan.addTab(self.yanmoxingxi, "")
        self.jishiben = QWidget()
        self.jishiben.setObjectName(u"jishiben")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(10)
        sizePolicy2.setVerticalStretch(10)
        sizePolicy2.setHeightForWidth(self.jishiben.sizePolicy().hasHeightForWidth())
        self.jishiben.setSizePolicy(sizePolicy2)
        self.jishiben.setAutoFillBackground(True)
        self.calendarWidget = QCalendarWidget(self.jishiben)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(1, 1, 248, 197))
        self.label = QLabel(self.jishiben)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(399, 1, 60, 20))
        font = QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.textBrowser = QTextBrowser(self.jishiben)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(399, 27, 256, 192))
        self.ZhuCaiDan.addTab(self.jishiben, "")

        self.gridLayout_3.addWidget(self.ZhuCaiDan, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.caidan = QMenuBar(MainWindow)
        self.caidan.setObjectName(u"caidan")
        self.caidan.setGeometry(QRect(0, 0, 1077, 23))
        self.ren_shi = QMenu(self.caidan)
        self.ren_shi.setObjectName(u"ren_shi")
        self.xiang_mu = QMenu(self.caidan)
        self.xiang_mu.setObjectName(u"xiang_mu")
        self.sheng_chan = QMenu(self.caidan)
        self.sheng_chan.setObjectName(u"sheng_chan")
        self.pin_zhi = QMenu(self.caidan)
        self.pin_zhi.setObjectName(u"pin_zhi")
        self.chang_ku = QMenu(self.caidan)
        self.chang_ku.setObjectName(u"chang_ku")
        self.cai_wu = QMenu(self.caidan)
        self.cai_wu.setObjectName(u"cai_wu")
        self.ti_xi = QMenu(self.caidan)
        self.ti_xi.setObjectName(u"ti_xi")
        self.ti_xi.setTearOffEnabled(False)
        self.zong_he_fen_xi = QMenu(self.caidan)
        self.zong_he_fen_xi.setObjectName(u"zong_he_fen_xi")
        self.chang_yong_ruan_jian = QMenu(self.caidan)
        self.chang_yong_ruan_jian.setObjectName(u"chang_yong_ruan_jian")
        self.bang_zhu = QMenu(self.caidan)
        self.bang_zhu.setObjectName(u"bang_zhu")
        MainWindow.setMenuBar(self.caidan)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setLayoutDirection(Qt.LeftToRight)
        self.toolBar.setAllowedAreas(Qt.AllToolBarAreas)
        self.toolBar.setOrientation(Qt.Vertical)
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.caidan.addAction(self.ren_shi.menuAction())
        self.caidan.addAction(self.xiang_mu.menuAction())
        self.caidan.addAction(self.sheng_chan.menuAction())
        self.caidan.addAction(self.pin_zhi.menuAction())
        self.caidan.addAction(self.chang_ku.menuAction())
        self.caidan.addAction(self.cai_wu.menuAction())
        self.caidan.addAction(self.ti_xi.menuAction())
        self.caidan.addAction(self.zong_he_fen_xi.menuAction())
        self.caidan.addAction(self.chang_yong_ruan_jian.menuAction())
        self.caidan.addAction(self.bang_zhu.menuAction())
        self.ren_shi.addAction(self.人员查询)
        self.ren_shi.addAction(self.加班记录)
        self.ren_shi.addAction(self.请假记录)
        self.ren_shi.addAction(self.考勤记录)
        self.ren_shi.addAction(self.后勤申请)
        self.xiang_mu.addAction(self.项目信息)
        self.xiang_mu.addAction(self.项目计划)
        self.sheng_chan.addAction(self.工程资料)
        self.sheng_chan.addAction(self.机台安排)
        self.sheng_chan.addAction(self.设备维修)
        self.pin_zhi.addAction(self.产品信息)
        self.pin_zhi.addAction(self.验模信息)
        self.pin_zhi.addAction(self.检具管理)
        self.pin_zhi.addAction(self.仪校管理)
        self.pin_zhi.addAction(self.品质异常)
        self.pin_zhi.addAction(self.交样信息)
        self.chang_ku.addAction(self.详细清单)
        self.chang_ku.addAction(self.入库管理)
        self.chang_ku.addAction(self.出库管理)
        self.chang_ku.addAction(self.退货管理)
        self.chang_ku.addAction(self.借用管理)
        self.chang_ku.addAction(self.库存管理)
        self.chang_ku.addAction(self.报废清单)
        self.cai_wu.addAction(self.采购申请)
        self.cai_wu.addAction(self.报销申请)
        self.cai_wu.addSeparator()
        self.cai_wu.addAction(self.采购管理)
        self.cai_wu.addAction(self.外协管理)
        self.ti_xi.addAction(self.体系查询)
        self.ti_xi.addAction(self.体系修改)
        self.zong_he_fen_xi.addAction(self.品质一览)
        self.zong_he_fen_xi.addAction(self.异常一览)
        self.zong_he_fen_xi.addAction(self.进度一览)
        self.zong_he_fen_xi.addAction(self.库存一览)
        self.chang_yong_ruan_jian.addAction(self.截图软件)
        self.chang_yong_ruan_jian.addAction(self.翻译软件)
        self.chang_yong_ruan_jian.addAction(self.日历)
        self.bang_zhu.addAction(self.密码修改)
        self.bang_zhu.addAction(self.账号切换)
        self.bang_zhu.addAction(self.退出)
        self.bang_zhu.addSeparator()
        self.bang_zhu.addAction(self.皮肤)
        self.toolBar.addAction(self.人员查询)
        self.toolBar.addAction(self.加班记录)
        self.toolBar.addAction(self.请假记录)

        self.retranslateUi(MainWindow)
        self.退出.triggered.connect(MainWindow.close)

        self.ZhuCaiDan.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u98de\u4e91\u4fe1\u606f\u7ba1\u7406\u5e73\u53f0", None))
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.人员查询.setText(QCoreApplication.translate("MainWindow", u"\u4eba\u5458\u67e5\u8be2", None))
        self.加班记录.setText(QCoreApplication.translate("MainWindow", u"\u52a0\u73ed\u8bb0\u5f55", None))
        self.请假记录.setText(QCoreApplication.translate("MainWindow", u"\u8bf7\u5047\u8bb0\u5f55", None))
        self.考勤记录.setText(QCoreApplication.translate("MainWindow", u"\u8003\u52e4\u8bb0\u5f55", None))
        self.后勤申请.setText(QCoreApplication.translate("MainWindow", u"\u540e\u52e4\u7533\u8bf7", None))
        self.项目信息.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u4fe1\u606f", None))
        self.项目计划.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u8ba1\u5212", None))
        self.机台安排.setText(QCoreApplication.translate("MainWindow", u"\u673a\u53f0\u5b89\u6392", None))
        self.设备维修.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u5907\u7ef4\u4fee", None))
        self.产品信息.setText(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u4fe1\u606f", None))
#if QT_CONFIG(tooltip)
        self.产品信息.setToolTip(QCoreApplication.translate("MainWindow", u"\u4ea7\u54c1\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.验模信息.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u4fe1\u606f", None))
#if QT_CONFIG(tooltip)
        self.验模信息.setToolTip(QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u4fe1\u606f", None))
#endif // QT_CONFIG(tooltip)
        self.检具管理.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u5177\u7ba1\u7406", None))
        self.仪校管理.setText(QCoreApplication.translate("MainWindow", u"\u4eea\u6821\u7ba1\u7406", None))
        self.品质异常.setText(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u5f02\u5e38", None))
        self.交样信息.setText(QCoreApplication.translate("MainWindow", u"\u4ea4\u6837\u4fe1\u606f", None))
        self.工程资料.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u7a0b\u8d44\u6599", None))
        self.详细清单.setText(QCoreApplication.translate("MainWindow", u"\u8be6\u7ec6\u6e05\u5355", None))
        self.入库管理.setText(QCoreApplication.translate("MainWindow", u"\u5165\u5e93\u7ba1\u7406", None))
        self.出库管理.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u5e93\u7ba1\u7406", None))
        self.退货管理.setText(QCoreApplication.translate("MainWindow", u"\u9000\u8d27\u7ba1\u7406", None))
        self.借用管理.setText(QCoreApplication.translate("MainWindow", u"\u501f\u7528\u7ba1\u7406", None))
        self.库存管理.setText(QCoreApplication.translate("MainWindow", u"\u5e93\u5b58\u7ba1\u7406", None))
        self.报废清单.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u5e9f\u6e05\u5355", None))
        self.采购申请.setText(QCoreApplication.translate("MainWindow", u"\u91c7\u8d2d\u7533\u8bf7", None))
        self.品质一览.setText(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u4e00\u89c8", None))
        self.异常一览.setText(QCoreApplication.translate("MainWindow", u"\u5f02\u5e38\u4e00\u89c8", None))
        self.进度一览.setText(QCoreApplication.translate("MainWindow", u"\u8fdb\u5ea6\u4e00\u89c8", None))
        self.库存一览.setText(QCoreApplication.translate("MainWindow", u"\u5e93\u5b58\u4e00\u89c8", None))
        self.截图软件.setText(QCoreApplication.translate("MainWindow", u"\u622a\u56fe\u8f6f\u4ef6", None))
        self.翻译软件.setText(QCoreApplication.translate("MainWindow", u"\u7ffb\u8bd1\u8f6f\u4ef6", None))
        self.日历.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u5386", None))
        self.密码修改.setText(QCoreApplication.translate("MainWindow", u"\u5bc6\u7801\u4fee\u6539", None))
#if QT_CONFIG(shortcut)
        self.密码修改.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.账号切换.setText(QCoreApplication.translate("MainWindow", u"\u8d26\u53f7\u5207\u6362", None))
#if QT_CONFIG(shortcut)
        self.账号切换.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.退出.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(statustip)
        self.退出.setStatusTip(QCoreApplication.translate("MainWindow", u"\u70b9\u51fb\u6309\u94ae\u9000\u51fa\u7a0b\u5e8f\uff01", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.退出.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.皮肤.setText(QCoreApplication.translate("MainWindow", u"\u76ae\u80a4", None))
        self.采购管理.setText(QCoreApplication.translate("MainWindow", u"\u91c7\u8d2d\u7ba1\u7406", None))
        self.外协管理.setText(QCoreApplication.translate("MainWindow", u"\u5916\u534f\u7ba1\u7406", None))
        self.报销申请.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u9500\u7533\u8bf7", None))
        self.体系查询.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u67e5\u8be2", None))
        self.体系修改.setText(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u4fee\u6539", None))
        self.actioncsdc.setText(QCoreApplication.translate("MainWindow", u"csdc", None))
#if QT_CONFIG(statustip)
        self.ZhuCaiDan.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.ranwu), QCoreApplication.translate("MainWindow", u"\u4efb\u52a1\u680f", None))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.zhicaidan), QCoreApplication.translate("MainWindow", u"\u5b50\u83dc\u5355", None))
        self.toolButton_6.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.toolButton_4.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b", None))
        self.toolButton_3.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539", None))
        self.toolButton_8.setText(QCoreApplication.translate("MainWindow", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.toolButton_2.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.toolButton_5.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.toolButton.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.groupBox.setTitle("")
        self.chaxun.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u671f\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u90e8\u95e8\uff1a", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u53f7\uff1a", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u59d3\u540d\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u81f3", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u7b5b\u9009\u65b9\u5f0f\uff1a", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"\u5728\u804c\u4eba\u5458", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"\u5165\u804c\u65e5\u671f", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"\u751f\u65e5\u65e5\u671f", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"\u79bb\u804c\u4eba\u5458", None))

        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u90e8\u95e8", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"\u7ec4\u522b", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"\u804c\u4f4d", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u53f7", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"\u59d3\u540d", None));
        ___qtablewidgetitem6 = self.tableWidget.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"\u6027\u522b", None));
        ___qtablewidgetitem7 = self.tableWidget.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u7535\u8bdd", None));
        ___qtablewidgetitem8 = self.tableWidget.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"\u5165\u804c\u65e5\u671f", None));
        ___qtablewidgetitem9 = self.tableWidget.horizontalHeaderItem(9)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u751f\u65e5\u671f", None));
        ___qtablewidgetitem10 = self.tableWidget.horizontalHeaderItem(10)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"\u8eab\u4efd\u8bc1\u53f7", None));
        ___qtablewidgetitem11 = self.tableWidget.horizontalHeaderItem(11)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"\u5730\u5740", None));
        ___qtablewidgetitem12 = self.tableWidget.horizontalHeaderItem(12)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"\u5f85\u9047", None));
        ___qtablewidgetitem13 = self.tableWidget.horizontalHeaderItem(13)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u85aa\u65e5\u671f", None));
        ___qtablewidgetitem14 = self.tableWidget.horizontalHeaderItem(14)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"\u79bb\u804c\u65e5\u671f", None));
        ___qtablewidgetitem15 = self.tableWidget.horizontalHeaderItem(15)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"\u5907\u6ce8", None));
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.renyuanxinxi), QCoreApplication.translate("MainWindow", u"\u4eba\u5458\u4fe1\u606f", None))
        self.toolButton_7.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.toolButton_9.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b", None))
        self.toolButton_10.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539", None))
        self.toolButton_11.setText(QCoreApplication.translate("MainWindow", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.toolButton_12.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.toolButton_13.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.toolButton_14.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.groupBox_3.setTitle("")
        self.chaxun_2.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u671f\uff1a", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\uff1a", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7\uff1a", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u81f3", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"\u7b5b\u9009\u65b9\u5f0f\uff1a", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"\u4e1a\u52a1", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"\u9879\u76ee", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"\u8bbe\u8ba1", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"\u94b3\u5de5", None))

        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7\uff1a", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\u62c5\u5f53\u4eba\uff1a", None))
        self.comboBox_7.setItemText(0, QCoreApplication.translate("MainWindow", u"\u4e0b\u5355", None))
        self.comboBox_7.setItemText(1, QCoreApplication.translate("MainWindow", u"\u9996\u6837", None))
        self.comboBox_7.setItemText(2, QCoreApplication.translate("MainWindow", u"\u79fb\u6a21", None))

        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u79fb\u6a21\u9879\u76ee", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u5386\u53f2\u8bb0\u5f55", None))
        ___qtablewidgetitem16 = self.tableWidget_xm.horizontalHeaderItem(0)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        ___qtablewidgetitem17 = self.tableWidget_xm.horizontalHeaderItem(1)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7", None));
        ___qtablewidgetitem18 = self.tableWidget_xm.horizontalHeaderItem(2)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7", None));
        ___qtablewidgetitem19 = self.tableWidget_xm.horizontalHeaderItem(3)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u5177\u7b49\u7ea7", None));
        ___qtablewidgetitem20 = self.tableWidget_xm.horizontalHeaderItem(4)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"\u4e1a\u52a1\u62c5\u5f53", None));
        ___qtablewidgetitem21 = self.tableWidget_xm.horizontalHeaderItem(5)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u62c5\u5f53", None));
        ___qtablewidgetitem22 = self.tableWidget_xm.horizontalHeaderItem(6)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"\u8bbe\u8ba1\u62c5\u5f53", None));
        ___qtablewidgetitem23 = self.tableWidget_xm.horizontalHeaderItem(7)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"\u94b3\u5de5\u62c5\u5f53", None));
        ___qtablewidgetitem24 = self.tableWidget_xm.horizontalHeaderItem(8)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"\u94b3\u5de5\u7ec4\u522b", None));
        ___qtablewidgetitem25 = self.tableWidget_xm.horizontalHeaderItem(9)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"\u4e0b\u5355\u65e5\u671f", None));
        ___qtablewidgetitem26 = self.tableWidget_xm.horizontalHeaderItem(10)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"\u9996\u6837\u65e5\u671f", None));
        ___qtablewidgetitem27 = self.tableWidget_xm.horizontalHeaderItem(11)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"\u8981\u6c42\u79fb\u6a21\u65e5\u671f", None));
        ___qtablewidgetitem28 = self.tableWidget_xm.horizontalHeaderItem(12)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"\u5b9e\u9645\u79fb\u6a21\u65e5\u671f", None));
        ___qtablewidgetitem29 = self.tableWidget_xm.horizontalHeaderItem(13)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"\u5408\u683c/\u7279\u91c7", None));
        ___qtablewidgetitem30 = self.tableWidget_xm.horizontalHeaderItem(14)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"\u5907\u6ce8", None));
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.xiangmuxinxi), QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u4fe1\u606f", None))
        self.toolButton_15.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.toolButton_16.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b", None))
        self.toolButton_17.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539", None))
        self.toolButton_18.setText(QCoreApplication.translate("MainWindow", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.toolButton_19.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.toolButton_20.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.toolButton_21.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.groupBox_4.setTitle("")
        self.chaxun_3.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u671f\uff1a", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\uff1a", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7\uff1a", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"\u81f3", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7\uff1a", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u79fb\u6a21\u9879\u76ee", None))
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u5386\u53f2\u8bb0\u5f55", None))
        self.comboBox_18.setItemText(0, QCoreApplication.translate("MainWindow", u"\u6837\u54c1", None))
        self.comboBox_18.setItemText(1, QCoreApplication.translate("MainWindow", u"\u96f6\u4ef6", None))
        self.comboBox_18.setItemText(2, QCoreApplication.translate("MainWindow", u"\u68c0\u5177", None))

        self.label_33.setText(QCoreApplication.translate("MainWindow", u"\u7c7b\u578b\uff1a", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u4eba\u5458\uff1a", None))
        ___qtablewidgetitem31 = self.tableWidget_jc.horizontalHeaderItem(0)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        ___qtablewidgetitem32 = self.tableWidget_jc.horizontalHeaderItem(1)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7", None));
        ___qtablewidgetitem33 = self.tableWidget_jc.horizontalHeaderItem(2)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7", None));
        ___qtablewidgetitem34 = self.tableWidget_jc.horizontalHeaderItem(3)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u544a\u683c\u5f0f", None));
        ___qtablewidgetitem35 = self.tableWidget_jc.horizontalHeaderItem(4)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"\u53d8\u8584\u7387", None));
        ___qtablewidgetitem36 = self.tableWidget_jc.horizontalHeaderItem(5)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u65e5\u671f", None));
        ___qtablewidgetitem37 = self.tableWidget_jc.horizontalHeaderItem(6)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u76ee\u7684", None));
        ___qtablewidgetitem38 = self.tableWidget_jc.horizontalHeaderItem(7)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"\u6570\u91cf", None));
        ___qtablewidgetitem39 = self.tableWidget_jc.horizontalHeaderItem(8)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"\u578b\u9762", None));
        ___qtablewidgetitem40 = self.tableWidget_jc.horizontalHeaderItem(9)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"\u6599\u8fb9", None));
        ___qtablewidgetitem41 = self.tableWidget_jc.horizontalHeaderItem(10)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"\u5b54\u4f4d", None));
        ___qtablewidgetitem42 = self.tableWidget_jc.horizontalHeaderItem(11)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"\u7efc\u5408", None));
        ___qtablewidgetitem43 = self.tableWidget_jc.horizontalHeaderItem(12)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u4eba", None));
        ___qtablewidgetitem44 = self.tableWidget_jc.horizontalHeaderItem(13)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"\u8017\u65f6", None));
        ___qtablewidgetitem45 = self.tableWidget_jc.horizontalHeaderItem(14)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"\u5907\u6ce8", None));
        ___qtablewidgetitem46 = self.tableWidget_jc.horizontalHeaderItem(15)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"\u62a5\u544a\u5b58\u653e\u8def\u5f84", None));
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.jiancebaogao), QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u62a5\u544a", None))
        self.toolButton_22.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.toolButton_23.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u770b", None))
        self.toolButton_24.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539", None))
        self.toolButton_25.setText(QCoreApplication.translate("MainWindow", u"\u6d41\u7a0b\u8df3\u8f6c", None))
        self.toolButton_26.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.toolButton_27.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.toolButton_28.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.groupBox_5.setTitle("")
        self.chaxun_4.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u8be2", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"\u65e5\u671f\uff1a", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\uff1a", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7\uff1a", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"\u81f3", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7\uff1a", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u79fb\u6a21\u9879\u76ee", None))
        self.checkBox_8.setText(QCoreApplication.translate("MainWindow", u"\u5305\u62ec\u5386\u53f2\u8bb0\u5f55", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u6536\u4eba\u5458\uff1a", None))
        ___qtablewidgetitem47 = self.tableWidget_ym.horizontalHeaderItem(0)
        ___qtablewidgetitem47.setText(QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        ___qtablewidgetitem48 = self.tableWidget_ym.horizontalHeaderItem(1)
        ___qtablewidgetitem48.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u53f7", None));
        ___qtablewidgetitem49 = self.tableWidget_ym.horizontalHeaderItem(2)
        ___qtablewidgetitem49.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u6237\u7f16\u53f7", None));
        ___qtablewidgetitem50 = self.tableWidget_ym.horizontalHeaderItem(3)
        ___qtablewidgetitem50.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u6536\u6b21\u6570", None));
        ___qtablewidgetitem51 = self.tableWidget_ym.horizontalHeaderItem(4)
        ___qtablewidgetitem51.setText(QCoreApplication.translate("MainWindow", u"\u94b3\u5de5\u62c5\u5f53", None));
        ___qtablewidgetitem52 = self.tableWidget_ym.horizontalHeaderItem(5)
        ___qtablewidgetitem52.setText(QCoreApplication.translate("MainWindow", u"\u94b3\u5de5\u7ec4\u522b", None));
        ___qtablewidgetitem53 = self.tableWidget_ym.horizontalHeaderItem(6)
        ___qtablewidgetitem53.setText(QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u62c5\u5f53", None));
        ___qtablewidgetitem54 = self.tableWidget_ym.horizontalHeaderItem(7)
        ___qtablewidgetitem54.setText(QCoreApplication.translate("MainWindow", u"\u9884\u9a8c\u65e5\u671f", None));
        ___qtablewidgetitem55 = self.tableWidget_ym.horizontalHeaderItem(8)
        ___qtablewidgetitem55.setText(QCoreApplication.translate("MainWindow", u"\u9884\u9a8c\u5b8c\u5584", None));
        ___qtablewidgetitem56 = self.tableWidget_ym.horizontalHeaderItem(9)
        ___qtablewidgetitem56.setText(QCoreApplication.translate("MainWindow", u"\u8fbe\u6210\u7387", None));
        ___qtablewidgetitem57 = self.tableWidget_ym.horizontalHeaderItem(10)
        ___qtablewidgetitem57.setText(QCoreApplication.translate("MainWindow", u"\u590d\u9a8c\u65e5\u671f", None));
        ___qtablewidgetitem58 = self.tableWidget_ym.horizontalHeaderItem(11)
        ___qtablewidgetitem58.setText(QCoreApplication.translate("MainWindow", u"\u590d\u9a8c\u95ee\u9898", None));
        ___qtablewidgetitem59 = self.tableWidget_ym.horizontalHeaderItem(12)
        ___qtablewidgetitem59.setText(QCoreApplication.translate("MainWindow", u"\u8fbe\u6210\u7387", None));
        ___qtablewidgetitem60 = self.tableWidget_ym.horizontalHeaderItem(13)
        ___qtablewidgetitem60.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u9a8c\u65e5\u671f", None));
        ___qtablewidgetitem61 = self.tableWidget_ym.horizontalHeaderItem(14)
        ___qtablewidgetitem61.setText(QCoreApplication.translate("MainWindow", u"\u5ba2\u9a8c\u95ee\u9898", None));
        ___qtablewidgetitem62 = self.tableWidget_ym.horizontalHeaderItem(15)
        ___qtablewidgetitem62.setText(QCoreApplication.translate("MainWindow", u"\u8fbe\u6210\u7387", None));
        ___qtablewidgetitem63 = self.tableWidget_ym.horizontalHeaderItem(16)
        ___qtablewidgetitem63.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u5217", None));
        ___qtablewidgetitem64 = self.tableWidget_ym.horizontalHeaderItem(17)
        ___qtablewidgetitem64.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u9a8c\u65e5\u671f", None));
        ___qtablewidgetitem65 = self.tableWidget_ym.horizontalHeaderItem(18)
        ___qtablewidgetitem65.setText(QCoreApplication.translate("MainWindow", u"\u7ec8\u9a8c\u95ee\u9898", None));
        ___qtablewidgetitem66 = self.tableWidget_ym.horizontalHeaderItem(19)
        ___qtablewidgetitem66.setText(QCoreApplication.translate("MainWindow", u"\u8fbe\u6210\u7387", None));
        ___qtablewidgetitem67 = self.tableWidget_ym.horizontalHeaderItem(20)
        ___qtablewidgetitem67.setText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84", None));
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.yanmoxingxi), QCoreApplication.translate("MainWindow", u"\u9a8c\u6a21\u4fe1\u606f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bb0\u4e8b\u672c", None))
        self.ZhuCaiDan.setTabText(self.ZhuCaiDan.indexOf(self.jishiben), QCoreApplication.translate("MainWindow", u"\u8bb0\u4e8b\u672c", None))
        self.ren_shi.setTitle(QCoreApplication.translate("MainWindow", u"\u4eba\u4e8b\u7ba1\u7406", None))
        self.xiang_mu.setTitle(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u7ba1\u7406", None))
        self.sheng_chan.setTitle(QCoreApplication.translate("MainWindow", u"\u751f\u4ea7\u7ba1\u7406", None))
        self.pin_zhi.setTitle(QCoreApplication.translate("MainWindow", u"\u54c1\u8d28\u7ba1\u7406", None))
        self.chang_ku.setTitle(QCoreApplication.translate("MainWindow", u"\u4ed3\u5e93\u7ba1\u7406", None))
        self.cai_wu.setTitle(QCoreApplication.translate("MainWindow", u"\u8d22\u52a1\u7ba1\u7406", None))
        self.ti_xi.setTitle(QCoreApplication.translate("MainWindow", u"\u4f53\u7cfb\u7ba1\u7406", None))
        self.zong_he_fen_xi.setTitle(QCoreApplication.translate("MainWindow", u"\u7efc\u5408\u5206\u6790", None))
        self.chang_yong_ruan_jian.setTitle(QCoreApplication.translate("MainWindow", u"\u5e38\u7528\u8f6f\u4ef6", None))
        self.bang_zhu.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

