# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主界面A2.ui',
# licensing of '主界面A2.ui' applies.
#
# Created: Tue May 26 08:16:47 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_zhu_jie_mian(object):
    def setupUi(self, zhu_jie_mian):
        zhu_jie_mian.setObjectName("zhu_jie_mian")
        zhu_jie_mian.setWindowModality(QtCore.Qt.NonModal)
        zhu_jie_mian.resize(1113, 685)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(zhu_jie_mian.sizePolicy().hasHeightForWidth())
        zhu_jie_mian.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/主题.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        zhu_jie_mian.setWindowIcon(icon)
        zhu_jie_mian.setStatusTip("")
        zhu_jie_mian.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(zhu_jie_mian)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 505))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setContentsMargins(1, 1, 0, 1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ZhuCaiDan = QtWidgets.QTabWidget(self.centralwidget)
        self.ZhuCaiDan.setEnabled(True)
        self.ZhuCaiDan.setMouseTracking(True)
        self.ZhuCaiDan.setTabletTracking(True)
        self.ZhuCaiDan.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ZhuCaiDan.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ZhuCaiDan.setAcceptDrops(True)
        self.ZhuCaiDan.setToolTipDuration(-1)
        self.ZhuCaiDan.setStatusTip("")
        self.ZhuCaiDan.setStyleSheet("")
        self.ZhuCaiDan.setObjectName("ZhuCaiDan")
        self.ranwu = QtWidgets.QWidget()
        self.ranwu.setObjectName("ranwu")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ranwu)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(self.ranwu)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.gridLayout_2.addWidget(self.calendarWidget_2, 3, 2, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.ranwu)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ranwu)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.ranwu)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 4, 0, 1, 2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.ranwu)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_2.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ranwu)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 3, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.ranwu)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.ranwu)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_11 = QtWidgets.QLabel(self.ranwu)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.ranwu)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.ranwu)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.textBrowser_3)
        self.label_9 = QtWidgets.QLabel(self.ranwu)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.ranwu)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.gridLayout_4.addLayout(self.formLayout, 0, 1, 1, 1)
        self.ZhuCaiDan.addTab(self.ranwu, "")
        self.zhicaidan = QtWidgets.QWidget()
        self.zhicaidan.setObjectName("zhicaidan")
        self.ZhuCaiDan.addTab(self.zhicaidan, "")
        self.renyuanxinxi = QtWidgets.QWidget()
        self.renyuanxinxi.setObjectName("renyuanxinxi")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.renyuanxinxi)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.renyuanxinxi)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 390, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.toolButton_6 = QtWidgets.QToolButton(self.layoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ICO/png/1110305.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon1)
        self.toolButton_6.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_6.addWidget(self.toolButton_6, 0, 9, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ICO/png/1081628.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon2)
        self.toolButton_8.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout_6.addWidget(self.toolButton_8, 0, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 0, 3, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ICO/png/1081656.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon3)
        self.toolButton_5.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_6.addWidget(self.toolButton_5, 0, 5, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ICO/png/1081676.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon4)
        self.toolButton.setIconSize(QtCore.QSize(36, 36))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_6.addWidget(self.toolButton, 0, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ICO/png/1081640.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon5)
        self.toolButton_2.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_6.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_6.addWidget(self.line_2, 0, 6, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.layoutWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ICO/png/1081662.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon6)
        self.toolButton_4.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_6.addWidget(self.toolButton_4, 0, 4, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ICO/png/1073170.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon7)
        self.toolButton_3.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_6.addWidget(self.toolButton_3, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 0, 8, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.renyuanxinxi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        self.gridLayout_5.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.renyuanxinxi)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.chaxun = QtWidgets.QPushButton(self.groupBox)
        self.chaxun.setEnabled(True)
        self.chaxun.setGeometry(QtCore.QRect(790, 9, 75, 23))
        self.chaxun.setObjectName("chaxun")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 10, 81, 20))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(81, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(81, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 10, 81, 20))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(81, 20))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(81, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(555, 11, 31, 16))
        self.label_5.setMaximumSize(QtCore.QSize(36, 16))
        self.label_5.setObjectName("label_5")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_2.setGeometry(QtCore.QRect(697, 10, 88, 20))
        self.dateEdit_2.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_2.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit_2.setCalendarPopup(True)
        self.dateEdit_2.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_2.setMaximumSize(QtCore.QSize(36, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 11, 31, 16))
        self.label_3.setMaximumSize(QtCore.QSize(36, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(290, 11, 31, 16))
        self.label_4.setMaximumSize(QtCore.QSize(36, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(680, 10, 16, 16))
        self.label_6.setObjectName("label_6")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit.setGeometry(QtCore.QRect(587, 10, 88, 20))
        self.dateEdit.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        self.label_13.setObjectName("label_13")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(470, 10, 81, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_8.setGeometry(QtCore.QRect(40, 10, 111, 20))
        self.comboBox_8.setMaximumSize(QtCore.QSize(800, 20))
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_5.addWidget(self.groupBox, 2, 0, 1, 1)
        self.ZhuCaiDan.addTab(self.renyuanxinxi, "")
        self.xiangmuxinxi = QtWidgets.QWidget()
        self.xiangmuxinxi.setObjectName("xiangmuxinxi")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.xiangmuxinxi)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.xiangmuxinxi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setAutoScroll(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(15)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(30, item)
        self.gridLayout_8.addWidget(self.tableWidget_2, 3, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.xiangmuxinxi)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 390, 60))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolButton_7 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_7.setIcon(icon1)
        self.toolButton_7.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_7.addWidget(self.toolButton_7, 0, 9, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_9.setIcon(icon2)
        self.toolButton_9.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_9.setAutoRaise(True)
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout_7.addWidget(self.toolButton_9, 0, 7, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_7.addWidget(self.line_4, 0, 3, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_10.setIcon(icon3)
        self.toolButton_10.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_10.setAutoRaise(True)
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout_7.addWidget(self.toolButton_10, 0, 5, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_11.setIcon(icon4)
        self.toolButton_11.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_11.setAutoRaise(True)
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout_7.addWidget(self.toolButton_11, 0, 0, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_12.setIcon(icon5)
        self.toolButton_12.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_12.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_12.setAutoRaise(True)
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout_7.addWidget(self.toolButton_12, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_7.addWidget(self.line_5, 0, 6, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_13.setIcon(icon6)
        self.toolButton_13.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout_7.addWidget(self.toolButton_13, 0, 4, 1, 1)
        self.toolButton_14 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.toolButton_14.setIcon(icon7)
        self.toolButton_14.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_14.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_14.setAutoRaise(True)
        self.toolButton_14.setObjectName("toolButton_14")
        self.gridLayout_7.addWidget(self.toolButton_14, 0, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_7.addWidget(self.line_6, 0, 8, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.xiangmuxinxi)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.chaxun_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.chaxun_2.setEnabled(True)
        self.chaxun_2.setGeometry(QtCore.QRect(1090, 10, 75, 23))
        self.chaxun_2.setObjectName("chaxun_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(755, 12, 31, 16))
        self.label_12.setMaximumSize(QtCore.QSize(36, 16))
        self.label_12.setObjectName("label_12")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_3.setGeometry(QtCore.QRect(897, 11, 88, 20))
        self.dateEdit_3.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_3.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_3.setCalendarPopup(True)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_14.setMaximumSize(QtCore.QSize(36, 16))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(120, 10, 31, 16))
        self.label_15.setMaximumSize(QtCore.QSize(36, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(880, 11, 16, 16))
        self.label_17.setObjectName("label_17")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_4.setGeometry(QtCore.QRect(787, 11, 88, 20))
        self.dateEdit_4.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_4.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_4.setCalendarPopup(True)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(610, 10, 60, 20))
        self.label_18.setMaximumSize(QtCore.QSize(60, 20))
        self.label_18.setObjectName("label_18")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 9, 51, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setGeometry(QtCore.QRect(40, 9, 69, 22))
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 9, 69, 22))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_5.setGeometry(QtCore.QRect(290, 9, 111, 22))
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(230, 10, 61, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(420, 10, 51, 20))
        self.label_20.setMaximumSize(QtCore.QSize(60, 20))
        self.label_20.setObjectName("label_20")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_6.setGeometry(QtCore.QRect(510, 9, 81, 22))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_7.setGeometry(QtCore.QRect(670, 10, 51, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(990, 2, 89, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setGeometry(QtCore.QRect(990, 20, 89, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_8.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.ZhuCaiDan.addTab(self.xiangmuxinxi, "")
        self.jiancebaogao = QtWidgets.QWidget()
        self.jiancebaogao.setObjectName("jiancebaogao")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.jiancebaogao)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.jiancebaogao)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 371, 60))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.toolButton_15 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_15.setIcon(icon6)
        self.toolButton_15.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_15.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_15.setAutoRaise(True)
        self.toolButton_15.setObjectName("toolButton_15")
        self.gridLayout_9.addWidget(self.toolButton_15, 0, 3, 1, 1)
        self.toolButton_16 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_16.setIcon(icon7)
        self.toolButton_16.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_16.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_16.setAutoRaise(True)
        self.toolButton_16.setObjectName("toolButton_16")
        self.gridLayout_9.addWidget(self.toolButton_16, 0, 2, 1, 1)
        self.toolButton_17 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_17.setIcon(icon2)
        self.toolButton_17.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_17.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_17.setAutoRaise(True)
        self.toolButton_17.setObjectName("toolButton_17")
        self.gridLayout_9.addWidget(self.toolButton_17, 0, 6, 1, 1)
        self.toolButton_18 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_18.setIcon(icon5)
        self.toolButton_18.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_18.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_18.setAutoRaise(True)
        self.toolButton_18.setObjectName("toolButton_18")
        self.gridLayout_9.addWidget(self.toolButton_18, 0, 1, 1, 1)
        self.toolButton_19 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_19.setIcon(icon4)
        self.toolButton_19.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_19.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_19.setAutoRaise(True)
        self.toolButton_19.setObjectName("toolButton_19")
        self.gridLayout_9.addWidget(self.toolButton_19, 0, 0, 1, 1)
        self.toolButton_20 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_20.setIcon(icon3)
        self.toolButton_20.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_20.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_20.setAutoRaise(True)
        self.toolButton_20.setObjectName("toolButton_20")
        self.gridLayout_9.addWidget(self.toolButton_20, 0, 4, 1, 1)
        self.toolButton_21 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.toolButton_21.setIcon(icon1)
        self.toolButton_21.setIconSize(QtCore.QSize(36, 36))
        self.toolButton_21.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_21.setAutoRaise(True)
        self.toolButton_21.setObjectName("toolButton_21")
        self.gridLayout_9.addWidget(self.toolButton_21, 0, 7, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.jiancebaogao)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.chaxun_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.chaxun_4.setEnabled(True)
        self.chaxun_4.setGeometry(QtCore.QRect(1050, 10, 75, 23))
        self.chaxun_4.setObjectName("chaxun_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(688, 12, 31, 16))
        self.label_27.setMaximumSize(QtCore.QSize(36, 16))
        self.label_27.setObjectName("label_27")
        self.dateEdit_7 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_7.setGeometry(QtCore.QRect(830, 11, 88, 20))
        self.dateEdit_7.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_7.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_7.setCalendarPopup(True)
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(9, 11, 31, 16))
        self.label_28.setMaximumSize(QtCore.QSize(36, 16))
        self.label_28.setStyleSheet("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(120, 10, 31, 16))
        self.label_29.setMaximumSize(QtCore.QSize(36, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(813, 11, 16, 16))
        self.label_30.setObjectName("label_30")
        self.dateEdit_8 = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_8.setGeometry(QtCore.QRect(720, 11, 88, 20))
        self.dateEdit_8.setMinimumSize(QtCore.QSize(88, 20))
        self.dateEdit_8.setMaximumSize(QtCore.QSize(88, 20))
        self.dateEdit_8.setCalendarPopup(True)
        self.dateEdit_8.setObjectName("dateEdit_8")
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(530, 10, 60, 20))
        self.label_31.setMaximumSize(QtCore.QSize(60, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(240, 10, 61, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(430, 10, 31, 20))
        self.label_33.setMaximumSize(QtCore.QSize(60, 20))
        self.label_33.setObjectName("label_33")
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_18.setGeometry(QtCore.QRect(460, 10, 51, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_8.setGeometry(QtCore.QRect(590, 10, 81, 20))
        self.lineEdit_8.setMinimumSize(QtCore.QSize(81, 20))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(81, 20))
        self.lineEdit_8.setDragEnabled(False)
        self.lineEdit_8.setReadOnly(False)
        self.lineEdit_8.setClearButtonEnabled(False)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setGeometry(QtCore.QRect(930, 2, 89, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setGeometry(QtCore.QRect(930, 20, 89, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.fontComboBox_4 = QtWidgets.QFontComboBox(self.groupBox_5)
        self.fontComboBox_4.setGeometry(QtCore.QRect(150, 9, 81, 22))
