# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '人员信息录入.ui',
# licensing of '人员信息录入.ui' applies.
#
# Created: Fri Aug  7 13:47:58 2020
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(635, 363)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICO/主题.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.xingming = QtWidgets.QLineEdit(Dialog)
        self.xingming.setGeometry(QtCore.QRect(50, 10, 81, 21))
        self.xingming.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xingming.setAutoFillBackground(False)
        self.xingming.setInputMask("")
        self.xingming.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.xingming.setObjectName("xingming")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.bumen = QtWidgets.QLineEdit(Dialog)
        self.bumen.setGeometry(QtCore.QRect(50, 40, 121, 21))
        self.bumen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bumen.setAutoFillBackground(False)
        self.bumen.setInputMask("")
        self.bumen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bumen.setObjectName("bumen")
        self.zhiwei = QtWidgets.QLineEdit(Dialog)
        self.zhiwei.setGeometry(QtCore.QRect(50, 70, 91, 21))
        self.zhiwei.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zhiwei.setAutoFillBackground(False)
        self.zhiwei.setInputMask("")
        self.zhiwei.setText("")
        self.zhiwei.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zhiwei.setObjectName("zhiwei")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 70, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gonghao = QtWidgets.QLineEdit(Dialog)
        self.gonghao.setGeometry(QtCore.QRect(190, 70, 71, 21))
        self.gonghao.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gonghao.setAutoFillBackground(False)
        self.gonghao.setInputMask("")
        self.gonghao.setText("")
        self.gonghao.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gonghao.setObjectName("gonghao")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(180, 40, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.zubie = QtWidgets.QLineEdit(Dialog)
        self.zubie.setGeometry(QtCore.QRect(220, 40, 171, 21))
        self.zubie.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zubie.setAutoFillBackground(False)
        self.zubie.setInputMask("")
        self.zubie.setText("")
        self.zubie.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.zubie.setObjectName("zubie")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(230, 10, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ruzhiriqi = QtWidgets.QLineEdit(Dialog)
        self.ruzhiriqi.setGeometry(QtCore.QRect(300, 10, 91, 21))
        self.ruzhiriqi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ruzhiriqi.setAutoFillBackground(False)
        self.ruzhiriqi.setInputMask("")
        self.ruzhiriqi.setText("")
        self.ruzhiriqi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ruzhiriqi.setObjectName("ruzhiriqi")
        self.lianxidianhua = QtWidgets.QLineEdit(Dialog)
        self.lianxidianhua.setGeometry(QtCore.QRect(80, 100, 121, 21))
        self.lianxidianhua.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lianxidianhua.setAutoFillBackground(False)
        self.lianxidianhua.setInputMask("")
        self.lianxidianhua.setText("")
        self.lianxidianhua.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lianxidianhua.setObjectName("lianxidianhua")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.xingbie = QtWidgets.QComboBox(Dialog)
        self.xingbie.setEnabled(True)
        self.xingbie.setGeometry(QtCore.QRect(180, 10, 41, 22))
        self.xingbie.setEditable(True)
        self.xingbie.setFrame(True)
        self.xingbie.setObjectName("xingbie")
        self.xingbie.addItem("")
        self.xingbie.setItemText(0, "")
        self.xingbie.addItem("")
        self.xingbie.addItem("")
        self.jinjilianxihaoma = QtWidgets.QLineEdit(Dialog)
        self.jinjilianxihaoma.setGeometry(QtCore.QRect(270, 130, 121, 21))
        self.jinjilianxihaoma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jinjilianxihaoma.setAutoFillBackground(False)
        self.jinjilianxihaoma.setInputMask("")
        self.jinjilianxihaoma.setText("")
        self.jinjilianxihaoma.setMaxLength(11)
        self.jinjilianxihaoma.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.jinjilianxihaoma.setObjectName("jinjilianxihaoma")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(170, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.jinjilianxiren = QtWidgets.QLineEdit(Dialog)
        self.jinjilianxiren.setGeometry(QtCore.QRect(100, 130, 71, 21))
        self.jinjilianxiren.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.jinjilianxiren.setAutoFillBackground(False)
        self.jinjilianxiren.setInputMask("")
        self.jinjilianxiren.setText("")
        self.jinjilianxiren.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.jinjilianxiren.setObjectName("jinjilianxiren")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(10, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.chushengriqi = QtWidgets.QLineEdit(Dialog)
        self.chushengriqi.setGeometry(QtCore.QRect(290, 100, 101, 21))
        self.chushengriqi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chushengriqi.setAutoFillBackground(False)
        self.chushengriqi.setInputMask("")
        self.chushengriqi.setText("")
        self.chushengriqi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.chushengriqi.setReadOnly(True)
        self.chushengriqi.setObjectName("chushengriqi")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(220, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 91, 21))
        self.label_14.setObjectName("label_14")
        self.shenfenzhenghaoma = QtWidgets.QLineEdit(Dialog)
        self.shenfenzhenghaoma.setGeometry(QtCore.QRect(100, 190, 291, 21))
        self.shenfenzhenghaoma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shenfenzhenghaoma.setAutoFillBackground(False)
        self.shenfenzhenghaoma.setInputMask("")
        self.shenfenzhenghaoma.setText("")
        self.shenfenzhenghaoma.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shenfenzhenghaoma.setObjectName("shenfenzhenghaoma")
        self.dizhi = QtWidgets.QLineEdit(Dialog)
        self.dizhi.setGeometry(QtCore.QRect(50, 220, 341, 21))
        self.dizhi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dizhi.setAutoFillBackground(False)
        self.dizhi.setInputMask("")
        self.dizhi.setText("")
        self.dizhi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dizhi.setObjectName("dizhi")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(10, 220, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(270, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gongzuonianfen = QtWidgets.QLineEdit(Dialog)
        self.gongzuonianfen.setGeometry(QtCore.QRect(340, 70, 51, 21))
        self.gongzuonianfen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gongzuonianfen.setAutoFillBackground(False)
        self.gongzuonianfen.setInputMask("")
        self.gongzuonianfen.setText("")
        self.gongzuonianfen.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gongzuonianfen.setObjectName("gongzuonianfen")
        self.tiaoxinriqi = QtWidgets.QLineEdit(Dialog)
        self.tiaoxinriqi.setGeometry(QtCore.QRect(270, 160, 121, 21))
        self.tiaoxinriqi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tiaoxinriqi.setAutoFillBackground(False)
        self.tiaoxinriqi.setInputMask("")
        self.tiaoxinriqi.setText("")
        self.tiaoxinriqi.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tiaoxinriqi.setObjectName("tiaoxinriqi")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(200, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(10, 250, 41, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.beizhu = QtWidgets.QLineEdit(Dialog)
        self.beizhu.setGeometry(QtCore.QRect(50, 250, 341, 111))
        self.beizhu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.beizhu.setAutoFillBackground(False)
        self.beizhu.setInputMask("")
        self.beizhu.setText("")
        self.beizhu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.beizhu.setObjectName("beizhu")
        self.queren = QtWidgets.QPushButton(Dialog)
        self.queren.setGeometry(QtCore.QRect(400, 290, 231, 31))
        self.queren.setObjectName("queren")
        self.chongzhi = QtWidgets.QPushButton(Dialog)
        self.chongzhi.setGeometry(QtCore.QRect(400, 330, 231, 31))
        self.chongzhi.setObjectName("chongzhi")
        self.paizhao = QtWidgets.QPushButton(Dialog)
        self.paizhao.setGeometry(QtCore.QRect(550, 250, 81, 31))
        self.paizhao.setObjectName("paizhao")
        self.dakaixiangji = QtWidgets.QPushButton(Dialog)
        self.dakaixiangji.setGeometry(QtCore.QRect(410, 250, 81, 31))
        self.dakaixiangji.setObjectName("dakaixiangji")
        self.daiyu = QtWidgets.QDoubleSpinBox(Dialog)
        self.daiyu.setGeometry(QtCore.QRect(50, 160, 121, 22))
        self.daiyu.setDecimals(2)
        self.daiyu.setMaximum(999999999.99)
        self.daiyu.setObjectName("daiyu")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(390, 0, 241, 251))
        self.widget.setObjectName("widget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.xingming, self.ruzhiriqi)
        Dialog.setTabOrder(self.ruzhiriqi, self.bumen)
        Dialog.setTabOrder(self.bumen, self.zubie)
        Dialog.setTabOrder(self.zubie, self.zhiwei)
        Dialog.setTabOrder(self.zhiwei, self.gonghao)
        Dialog.setTabOrder(self.gonghao, self.gongzuonianfen)
        Dialog.setTabOrder(self.gongzuonianfen, self.lianxidianhua)
        Dialog.setTabOrder(self.lianxidianhua, self.jinjilianxiren)
        Dialog.setTabOrder(self.jinjilianxiren, self.jinjilianxihaoma)
        Dialog.setTabOrder(self.jinjilianxihaoma, self.daiyu)
        Dialog.setTabOrder(self.daiyu, self.shenfenzhenghaoma)
        Dialog.setTabOrder(self.shenfenzhenghaoma, self.dizhi)
        Dialog.setTabOrder(self.dizhi, self.beizhu)
        Dialog.setTabOrder(self.beizhu, self.dakaixiangji)
        Dialog.setTabOrder(self.dakaixiangji, self.paizhao)
        Dialog.setTabOrder(self.paizhao, self.queren)
        Dialog.setTabOrder(self.queren, self.chongzhi)
        Dialog.setTabOrder(self.chongzhi, self.tiaoxinriqi)
        Dialog.setTabOrder(self.tiaoxinriqi, self.chushengriqi)
        Dialog.setTabOrder(self.chushengriqi, self.xingbie)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "人员信息", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "姓名:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "性别:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "部门:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "职位:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "工号:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "待遇:", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "组别:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Dialog", "入职日期:", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Dialog", "联系电话:", None, -1))
        self.xingbie.setItemText(1, QtWidgets.QApplication.translate("Dialog", "男", None, -1))
        self.xingbie.setItemText(2, QtWidgets.QApplication.translate("Dialog", "女", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Dialog", "紧急联系电话:", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("Dialog", "紧急联系人:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "出生日期:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "身份证号码：", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog", "地址:", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("Dialog", "工作年份:", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog", "调薪日期:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "备注:", None, -1))
        self.queren.setText(QtWidgets.QApplication.translate("Dialog", "确认", None, -1))
        self.chongzhi.setText(QtWidgets.QApplication.translate("Dialog", "重置", None, -1))
        self.paizhao.setText(QtWidgets.QApplication.translate("Dialog", "拍照", None, -1))
        self.dakaixiangji.setText(QtWidgets.QApplication.translate("Dialog", "打开相机", None, -1))
        self.daiyu.setPrefix(QtWidgets.QApplication.translate("Dialog", "$ ", None, -1))

